"""
Training data for the SIH26093 atrocity categories (Round 18/19).

Adds seven harm categories plus one context category to the synthetic
corpus, in the same four "languages" the rest of the corpus uses:
  en  English · hi  Hindi (Devanagari) · gu  Gujarati · rom  romanised
  Hindi/Gujarati as typed on a phone.

Same rules as expressions.py / templates.py:
  - EVERYTHING HERE IS SYNTHETIC. Written to resemble what survivors of
    caste atrocities tell a helpline; no real caller data was used.
  - Wording deliberately differs from the phrase list in
    backend/lexicon.py, so the model learns the category from varied
    phrasing instead of memorising what the rules already catch.
  - The Hindi and Gujarati lines still need native-speaker review.

Merged into EXPRESSIONS / TEMPLATES / NEUTRAL / CO_OCCURRENCE at the
bottom of expressions.py and templates.py.
"""

ATROCITY_EXPRESSIONS = {
    "caste_atrocity": {
        "en": [
            "they said people of our caste should not dare to sit on a chair in front of them",
            "the teacher makes my son sweep the classroom because of who we are",
            "at the wedding they served us outside on the ground, away from everyone",
            "they wiped the handpump after my daughter touched it",
            "they shouted our caste name and laughed while the whole market watched",
            "my husband was made to touch their feet and apologise for walking past their house with shoes on",
            "they said a dalit groom will never ride a horse through this village",
            "they would not let us cremate my grandmother at the common ground",
            "my employer keeps a separate cup for me and calls it the dalit cup",
            "they spat on me and said my people are born to clean their drains",
        ],
        "hi": [
            "उन्होंने कहा तुम्हारी जाति वाले कुर्सी पर नहीं बैठ सकते",
            "मास्टर मेरे बेटे से ही झाड़ू लगवाता है क्योंकि हम दलित हैं",
            "शादी में हमें सबसे अलग जमीन पर खाना परोसा",
            "मेरी बेटी ने हैंडपंप छुआ तो उन्होंने उसे धोया",
            "पूरे बाजार के सामने हमारी जाति का नाम लेकर हंसे",
            "मेरे पति से उनके पैर छुआकर माफी मंगवाई",
        ],
        "gu": [
            "એમણે કહ્યું તમારી જાતિના લોકો ખુરશી પર ન બેસી શકે",
            "માસ્તર મારા દીકરા પાસે જ ઝાડુ કઢાવે છે કારણ કે અમે દલિત છીએ",
            "લગ્નમાં અમને બધાથી અલગ જમીન પર જમાડ્યા",
            "આખી બજાર સામે અમારી જાતિનું નામ લઈને હસ્યા",
            "મારી દીકરીએ હેન્ડપંપ અડ્યો તો એમણે ધોઈ નાખ્યો",
        ],
        "rom": [
            "unhone kaha tumhari jaati wale kursi pe nahi baith sakte",
            "master mere bete se hi jhaadu lagwata hai kyunki hum dalit hai",
            "shaadi me hume sabse alag zameen pe khana diya",
            "poore bazaar ke saamne hamari jaati ka naam lekar hase",
            "tamari jati na loko khurshi par na besi shake evu kidhu",
            "mere pati se unke pair chhukar maafi mangwayi",
        ],
    },
    "rape_sexual_violence": {
        "en": [
            "what they did to my daughter in the sugarcane field i cannot even say out loud",
            "he held me down in the storeroom and i could not stop him",
            "they took turns with her while one of them kept watch",
            "the contractor called me to the site office at night and forced himself on me",
            "my twelve year old came home bleeding and said the older boys hurt her there",
            "they made a video of what they did to me and are showing it around",
            "i was assaulted by the landlord's son and now i am pregnant",
            "he said nobody will believe a girl from our caste and then he attacked me",
        ],
        "hi": [
            "खेत में उन्होंने मेरी बेटी के साथ जो किया वो मैं बोल भी नहीं सकती",
            "गोदाम में उसने मुझे दबोच लिया और मैं कुछ नहीं कर पाई",
            "ठेकेदार ने रात को बुलाया और मेरे साथ जबरदस्ती की",
            "मेरी बारह साल की बेटी खून से लथपथ घर आई",
            "उन्होंने मेरे साथ गलत काम करके वीडियो बना लिया",
            "मालिक के बेटे ने मेरे साथ गलत किया और अब मैं पेट से हूं",
        ],
        "gu": [
            "ખેતરમાં એમણે મારી દીકરી સાથે જે કર્યું એ હું બોલી પણ નથી શકતી",
            "ગોડાઉનમાં એણે મને પકડી લીધી અને હું કંઈ ન કરી શકી",
            "કોન્ટ્રાક્ટરે રાત્રે બોલાવીને મારી સાથે જબરદસ્તી કરી",
            "એમણે મારી સાથે ખોટું કરીને વિડિયો બનાવી લીધો",
            "મારી બાર વર્ષની દીકરી લોહીલુહાણ થઈને ઘરે આવી",
        ],
        "rom": [
            "khet me unhone meri beti ke saath jo kiya wo main bol bhi nahi sakti",
            "godown me usne mujhe daboch liya aur main kuch nahi kar paayi",
            "thekedar ne raat ko bulaya aur mere saath zabardasti ki",
            "unhone mere saath galat kaam karke video bana liya",
            "mari dikri sathe khetar ma khotu karyu",
            "meri barah saal ki beti khoon se lathpath ghar aayi",
        ],
    },
    "family_murder": {
        "en": [
            "we found my brother's body near the canal two days after he went missing",
            "they poured kerosene on my father and set him alight in front of the temple",
            "my son was beaten until he stopped breathing, over a mobile phone",
            "my husband never came home, they killed him over the land",
            "they hanged my uncle from a tree and said it was suicide",
            "my mother died of her injuries after they attacked our house",
            "the post mortem says my brother was strangled",
        ],
        "hi": [
            "भाई गायब हुआ था, दो दिन बाद नहर के पास उसकी लाश मिली",
            "मंदिर के सामने पिताजी पर मिट्टी का तेल डालकर आग लगा दी",
            "मोबाइल के झगड़े में बेटे को इतना मारा कि सांस रुक गई",
            "जमीन के लिए मेरे पति को मार दिया गया",
            "चाचा को पेड़ से लटका दिया और कहते हैं आत्महत्या है",
            "हमले में लगी चोटों से मां नहीं बच पाई",
        ],
        "gu": [
            "ભાઈ ગુમ થયો હતો, બે દિવસ પછી નહેર પાસે એની લાશ મળી",
            "મંદિર સામે પપ્પા પર કેરોસીન છાંટીને આગ ચાંપી દીધી",
            "જમીન માટે મારા પતિને મારી નાખવામાં આવ્યા",
            "હુમલામાં વાગેલી ઈજાઓથી મમ્મી બચી ન શકી",
        ],
        "rom": [
            "bhai gayab hua tha do din baad nahar ke paas uski laash mili",
            "mandir ke saamne papa pe mitti ka tel daal kar aag laga di",
            "mobile ke jhagde me bete ko itna maara ki saans ruk gayi",
            "zameen ke liye mere pati ko maar diya gaya",
            "chacha ko ped se latka diya aur kehte hai aatmahatya hai",
            "bhai ni laash naher paase mali",
        ],
    },
    "witness_intimidation": {
        "en": [
            "they left a message that my daughter's wedding will not happen if i keep going to court",
            "the accused sat next to me outside the courtroom and whispered what they would do",
            "someone offered my husband a lakh rupees to say he did not see anything",
            "since they came out on bail they park outside our house every evening",
            "their lawyer told me it would be safer for my family if i forgot what i saw",
            "they want me to sign a paper saying it was a misunderstanding",
        ],
        "hi": [
            "संदेश भेजा है कि कोर्ट जाती रही तो बेटी की शादी नहीं होने देंगे",
            "कोर्ट के बाहर आरोपी मेरे पास बैठकर धमकाते रहे",
            "मेरे पति को कुछ न देखने की बात कहने के लिए एक लाख देने की बात की",
            "जमानत पर छूटने के बाद से रोज शाम घर के बाहर खड़े रहते हैं",
            "कागज पर लिखवाना चाहते हैं कि गलतफहमी हो गई थी",
        ],
        "gu": [
            "સંદેશો મોકલ્યો કે કોર્ટમાં જશો તો દીકરીના લગ્ન નહીં થવા દઈએ",
            "કોર્ટની બહાર આરોપીઓ મારી પાસે બેસીને ધમકાવતા રહ્યા",
            "કાગળ પર લખાવવા માંગે છે કે ગેરસમજ થઈ હતી",
            "જામીન પર છૂટ્યા પછી રોજ સાંજે ઘર બહાર ઊભા રહે છે",
        ],
        "rom": [
            "message bheja hai ki court jaati rahi to beti ki shaadi nahi hone denge",
            "court ke bahar aaropi mere paas baith kar dhamkate rahe",
            "kaagaz pe likhwana chahte hai ki galatfehmi ho gayi thi",
            "jamanat pe chhootne ke baad roz shaam ghar ke bahar khade rehte hai",
            "court ma jaso to dikri na lagan nahi thava daiye",
        ],
    },
    "social_boycott": {
        "en": [
            "the flour mill owner will not grind our wheat any more",
            "no one in the colony will hire us for the harvest this year",
            "the barber was fined for cutting my son's hair",
            "they drummed through the village announcing that anyone who talks to us pays a fine",
            "we have to walk four kilometres for water because they locked the tap",
            "the milk dairy has stopped taking our milk",
        ],
        "hi": [
            "चक्की वाला अब हमारा गेहूं नहीं पीसता",
            "इस साल कटाई के लिए कोई हमें काम पर नहीं रखता",
            "मेरे बेटे के बाल काटने पर नाई पर जुर्माना लगा दिया",
            "ढोल बजाकर एलान किया कि हमसे बात करने वाले पर दंड लगेगा",
            "नल पर ताला लगा दिया, पानी के लिए चार किलोमीटर जाते हैं",
        ],
        "gu": [
            "ઘંટીવાળો હવે અમારા ઘઉં દળતો નથી",
            "આ વર્ષે કાપણી માટે કોઈ અમને કામ પર નથી રાખતું",
            "ઢોલ વગાડીને જાહેર કર્યું કે અમારી સાથે વાત કરનારને દંડ થશે",
            "નળ પર તાળું મારી દીધું, પાણી માટે દૂર જવું પડે છે",
        ],
        "rom": [
            "chakki wala ab hamara gehu nahi peesta",
            "is saal katai ke liye koi hume kaam pe nahi rakhta",
            "dhol bajakar elaan kiya ki humse baat karne wale pe dand lagega",
            "nal pe taala laga diya paani ke liye door jaana padta hai",
            "dudh ni dairy e amaru dudh levanu bandh karyu",
        ],
    },
    "displacement_arson": {
        "en": [
            "we are sleeping at the bus stand since they pulled down our hut",
            "the mob came with petrol cans and the whole row of houses went up",
            "they fenced off the plot the government gave us and put their own lock",
            "our goats and our shed were burnt and there is nothing left to go back to",
            "we left the village at night with just the clothes we had on",
            "the bulldozer came without any notice and our house was gone in an hour",
        ],
        "hi": [
            "झोपड़ी गिरा दी तब से बस अड्डे पर सो रहे हैं",
            "भीड़ पेट्रोल लेकर आई और पूरी बस्ती जल गई",
            "सरकार का दिया प्लॉट घेरकर अपना ताला लगा दिया",
            "बकरियां और छप्पर जल गए, लौटने को कुछ नहीं बचा",
            "रात को जो कपड़े पहने थे उन्हीं में गांव छोड़ आए",
        ],
        "gu": [
            "ઝૂંપડું તોડી નાખ્યું ત્યારથી બસ સ્ટેન્ડ પર સૂઈએ છીએ",
            "ટોળું પેટ્રોલ લઈને આવ્યું અને આખી વસ્તી સળગી ગઈ",
            "સરકારે આપેલો પ્લોટ વાળીને પોતાનું તાળું મારી દીધું",
            "રાત્રે પહેરેલા કપડે જ ગામ છોડીને આવ્યા",
        ],
        "rom": [
            "jhopdi gira di tab se bus adde pe so rahe hai",
            "bheed petrol lekar aayi aur poori basti jal gayi",
            "sarkar ka diya plot gher kar apna taala laga diya",
            "raat ko jo kapde pehne the unhi me gaon chhod aaye",
            "zupdu todi nakhyu tyarthi bus stand par suie chhie",
        ],
    },
    "police_noncooperation": {
        "en": [
            "the munshi at the thana said come back after the festival and we will see",
            "they wrote a small quarrel in the report when my brother's head was broken",
            "the officer sat with the accused and drank tea while i waited outside",
            "four months and the investigation officer has not even visited the spot",
            "they told me cases like mine are false and i should not waste their time",
            "i gave a written complaint and they refused to give me a receipt",
        ],
        "hi": [
            "थाने का मुंशी बोला त्योहार के बाद आना फिर देखेंगे",
            "भाई का सिर फूटा था पर रिपोर्ट में मामूली झगड़ा लिख दिया",
            "मैं बाहर इंतजार करती रही और दरोगा आरोपियों के साथ चाय पीता रहा",
            "चार महीने हो गए जांच अधिकारी मौके पर भी नहीं आया",
            "लिखित शिकायत दी पर रसीद देने से मना कर दिया",
        ],
        "gu": [
            "થાણાના મુનશીએ કહ્યું તહેવાર પછી આવજો પછી જોઈશું",
            "ભાઈનું માથું ફૂટ્યું હતું પણ રિપોર્ટમાં નાનો ઝઘડો લખી નાખ્યો",
            "ચાર મહિના થયા તપાસ અધિકારી સ્થળ પર પણ નથી આવ્યા",
            "લેખિત ફરિયાદ આપી પણ પહોંચ આપવાની ના પાડી",
        ],
        "rom": [
            "thane ka munshi bola tyohar ke baad aana phir dekhenge",
            "bhai ka sir phoota tha par report me mamuli jhagda likh diya",
            "chaar mahine ho gaye jaanch adhikari mauke pe bhi nahi aaya",
            "likhit shikayat di par raseed dene se mana kar diya",
            "police station ma fariyad lidhi j nahi",
        ],
    },
    "atrocity_context": {
        "en": [
            "we are from a dalit family in the lower part of the village",
            "our family belongs to a scheduled caste",
            "i am an adivasi woman from the forest area",
            "we live in the harijan basti at the edge of the village",
            "our people are a scheduled tribe",
            "we are landless labourers from the sc community",
            "my husband is from the valmiki samaj",
        ],
        "hi": [
            "हम दलित परिवार से हैं",
            "हमारा परिवार अनुसूचित जाति का है",
            "मैं आदिवासी महिला हूं",
            "हम गांव के किनारे वाली बस्ती में रहते हैं",
            "हम भूमिहीन मजदूर हैं और अनुसूचित जाति से हैं",
        ],
        "gu": [
            "અમે દલિત પરિવારમાંથી છીએ",
            "અમારો પરિવાર અનુસૂચિત જાતિનો છે",
            "હું આદિવાસી મહિલા છું",
            "અમે ગામના છેવાડે આવેલા વાસમાં રહીએ છીએ",
        ],
        "rom": [
            "hum dalit parivar se hai",
            "hamara parivar anusuchit jaati ka hai",
            "main adivasi mahila hu",
            "ame dalit parivar mathi chhie",
            "hum bhoomiheen mazdoor hai sc samaj se",
        ],
    },
}

# Everyday and administrative messages a helpline actually receives.
# The Round 17 model had seen too few of these: it put "i feel a bit
# tired after work" in High and a caste-certificate question in
# Critical. These are the negative class that keeps it honest.
ATROCITY_NEUTRAL = {
    "en": [
        "i want to know the status of my relief compensation application",
        "how do i apply for a caste certificate online",
        "when will the second instalment of the relief amount come",
        "please give me the address of the district social welfare office",
        "i need details about the post matric scholarship for sc students",
        "please update the mobile number on my complaint",
        "the officer called me back yesterday, thank you for the help",
        "i felt a little tired after the long shift today",
        "my exams start next week so i am busy with studies",
        "which documents are needed for the compensation claim",
        "is this helpline open on sundays and holidays",
        "i just wanted to thank your team, my matter is resolved",
        "what is my docket number, i forgot to write it down",
        "can i file the complaint in gujarati instead of hindi",
        "my brother wants to know about the stand up india loan",
        "the hearing date has been fixed for next month",
        "how do i get a copy of the fir for the court",
        "i am calling on behalf of my father who cannot hear well",
    ],
    "hi": [
        "मेरी राहत राशि की अर्जी का क्या हुआ जानना है",
        "जाति प्रमाण पत्र के लिए ऑनलाइन आवेदन कैसे करें",
        "राहत राशि की दूसरी किस्त कब आएगी",
        "जिला समाज कल्याण कार्यालय का पता बता दीजिए",
        "एससी छात्रों की छात्रवृत्ति के बारे में जानकारी चाहिए",
        "मेरी शिकायत में मोबाइल नंबर बदलना है",
        "अधिकारी ने कल फोन किया था, मदद के लिए धन्यवाद",
        "आज लंबी ड्यूटी के बाद थोड़ी थकान है",
        "मुआवजे के लिए कौन से कागज चाहिए",
        "मेरा डॉकेट नंबर क्या है, लिखना भूल गई",
        "कोर्ट की तारीख अगले महीने की लगी है",
    ],
    "gu": [
        "મારી રાહત રકમની અરજીનું શું થયું એ જાણવું છે",
        "જાતિના દાખલા માટે ઓનલાઈન અરજી કેવી રીતે કરવી",
        "રાહત રકમનો બીજો હપ્તો ક્યારે આવશે",
        "જિલ્લા સમાજ કલ્યાણ કચેરીનું સરનામું આપો",
        "મારી ફરિયાદમાં મોબાઈલ નંબર બદલવો છે",
        "અધિકારીએ કાલે ફોન કર્યો હતો, મદદ માટે આભાર",
        "આજે લાંબી નોકરી પછી થોડો થાક લાગે છે",
        "વળતર માટે કયા કાગળો જોઈએ",
        "કોર્ટની તારીખ આવતા મહિને છે",
    ],
    "rom": [
        "meri rahat rashi ki arzi ka kya hua janna hai",
        "jaati praman patra ke liye online apply kaise kare",
        "rahat rashi ki doosri kisht kab aayegi",
        "jila samaj kalyan office ka address bata dijiye",
        "meri shikayat me mobile number badalna hai",
        "officer ne kal phone kiya tha thank you",
        "aaj lambi duty ke baad thodi thakan hai",
        "muavze ke liye kaun se kagaz chahiye",
        "mara docket number shu chhe",
        "court ni tarikh aavta mahine chhe",
    ],
}

ATROCITY_CO_OCCURRENCE = {
    "caste_atrocity": ["atrocity_context", "physical_safety_abuse", "social_boycott", "severe_trauma_fear"],
    "rape_sexual_violence": ["atrocity_context", "severe_trauma_fear", "witness_intimidation", "police_noncooperation"],
    "family_murder": ["atrocity_context", "severe_trauma_fear", "witness_intimidation", "depression_hopelessness"],
    "witness_intimidation": ["intimidation_threat", "severe_trauma_fear", "police_noncooperation"],
    "social_boycott": ["atrocity_context", "caste_atrocity", "financial_exploitation", "social_isolation"],
    "displacement_arson": ["atrocity_context", "physical_safety_abuse", "vulnerability_context"],
    "police_noncooperation": ["legal_dispute", "atrocity_context", "witness_intimidation"],
    "atrocity_context": ["caste_atrocity", "social_boycott", "legal_dispute"],
}


ATROCITY_TEMPLATES = {
    # ----------------------------------------------------------------
    "caste_atrocity": {
        "en": {
            "slots": {
                "who": ["the upper caste men", "the sarpanch", "the landlord's family",
                        "people from the other caste", "the village head", "my employer",
                        "the men from the main village", "our upper caste neighbours"],
                "act": ["abused me using my caste", "shouted a caste slur at me in front of everyone",
                        "said people like us should stay in our place", "did not let me enter the temple",
                        "made me eat separately from the others", "refused to let our children sit with theirs",
                        "humiliated my father for being dalit", "insulted my mother's caste in public",
                        "forced us to do their dirty work because of our caste",
                        "threw away the water i had touched", "stopped our groom from riding the horse",
                        "made my son clean their toilets because of our caste"],
                "when": ["yesterday", "in front of the whole village", "at the panchayat meeting",
                         "every time we go to the well", "during the festival", "last week",
                         "again today", "for years now"],
            },
            "patterns": [
                "{who} {act} {when}", "{when} {who} {act}", "because we are dalit {who} {act}",
                "{who} {act} and nobody stopped them", "it is humiliating, {who} {act} {when}",
                "i am ashamed to say it but {who} {act}",
            ],
        },
        "hi": {
            "slots": {
                "who": ["ऊंची जाति के लोगों ने", "सरपंच ने", "मालिक के परिवार ने", "गांव के मुखिया ने",
                        "पड़ोस के लोगों ने", "ठेकेदार ने"],
                "act": ["जाति का नाम लेकर गाली दी", "सबके सामने जातिसूचक शब्द कहे", "मंदिर में घुसने नहीं दिया",
                        "हमें अलग बर्तन में खाना दिया", "हमारे बच्चों को अलग बैठाया",
                        "मेरे पिता को दलित होने की वजह से अपमानित किया", "हमें कुएं से पानी नहीं भरने दिया",
                        "दूल्हे को घोड़ी पर नहीं चढ़ने दिया", "हमारी जाति को लेकर ताने मारे",
                        "नीच जाति कहकर भगा दिया"],
                "when": ["कल", "पूरे गांव के सामने", "पंचायत में", "त्योहार के दिन", "पिछले हफ्ते",
                         "आज फिर", "सालों से"],
            },
            "patterns": [
                "{who} {when} {act}", "{when} {who} {act}", "हम दलित हैं इसलिए {who} {act}",
                "{who} {act} और किसी ने नहीं रोका", "बहुत अपमान हुआ, {who} {when} {act}",
            ],
        },
        "gu": {
            "slots": {
                "who": ["ઊંચી જાતિના લોકોએ", "સરપંચે", "માલિકના પરિવારે", "ગામના મુખીએ", "પડોશીઓએ"],
                "act": ["જાતિનું નામ લઈને ગાળો આપી", "બધાની સામે જાતિવાચક શબ્દો કહ્યા", "મંદિરમાં જવા ન દીધા",
                        "અમને અલગ વાસણમાં જમવાનું આપ્યું", "અમારા બાળકોને અલગ બેસાડ્યા",
                        "દલિત હોવાને કારણે મારા પપ્પાનું અપમાન કર્યું", "કૂવેથી પાણી ભરવા ન દીધું",
                        "વરરાજાને ઘોડી પર ન બેસવા દીધો"],
                "when": ["ગઈ કાલે", "આખા ગામ સામે", "પંચાયતમાં", "તહેવારના દિવસે", "ગયા અઠવાડિયે", "આજે ફરી"],
            },
            "patterns": [
                "{who} {when} {act}", "{when} {who} {act}", "અમે દલિત છીએ એટલે {who} {act}",
                "{who} {act} અને કોઈએ રોક્યા નહીં",
            ],
        },
        "rom": {
            "slots": {
                "who": ["unchi jaati ke logo ne", "sarpanch ne", "malik ke parivar ne", "gaon ke mukhiya ne",
                        "padosi logo ne", "unchi jati na loko e"],
                "act": ["jaati ka naam lekar gaali di", "sabke saamne jaatisuchak shabd bole",
                        "mandir me ghusne nahi diya", "hume alag bartan me khana diya", "bachho ko alag bithaya",
                        "dalit hone ki wajah se papa ka apmaan kiya", "kuen se paani nahi bharne diya",
                        "jati na naame gaalo aapi", "dulhe ko ghodi pe nahi chadhne diya"],
                "when": ["kal", "poore gaon ke saamne", "panchayat me", "tyohar ke din", "pichle hafte", "aaj phir"],
            },
            "patterns": [
                "{who} {when} {act}", "{when} {who} {act}", "hum dalit hai isliye {who} {act}",
                "{who} {act} aur kisi ne nahi roka",
            ],
        },
    },
    # ----------------------------------------------------------------
    "rape_sexual_violence": {
        "en": {
            "slots": {
                "who": ["three men from the village", "the landlord's son", "the contractor",
                        "two men i did not know", "the sarpanch's nephew", "my employer",
                        "boys from the upper caste"],
                "act": ["raped my daughter", "sexually assaulted me", "forced himself on me",
                        "dragged my sister into the field and assaulted her",
                        "took my niece away and violated her", "gang raped a girl from our colony",
                        "tore my clothes and assaulted me", "sexually abused my minor daughter",
                        "molested and then raped my wife"],
                "when": ["last night", "when i was going to the fields", "on the way back from work",
                         "two days ago", "when nobody was home", "after dark", "while my husband was away"],
                "extra": ["she has not stopped crying since", "they recorded a video and are threatening to share it",
                          "we have not told the police yet", "she needs to see a doctor",
                          "i cannot even say the words properly"],
            },
            "patterns": [
                "{who} {act} {when}", "{when} {who} {act}", "{who} {act} and {extra}",
                "i do not know how to say this but {who} {act}", "{who} {act} {when} and {extra}",
            ],
        },
        "hi": {
            "slots": {
                "who": ["गांव के तीन लोगों ने", "मालिक के बेटे ने", "ठेकेदार ने", "दो अनजान आदमियों ने",
                        "सरपंच के भतीजे ने", "ऊंची जाति के लड़कों ने"],
                "act": ["मेरी बेटी के साथ बलात्कार किया", "मेरे साथ जबरदस्ती की",
                        "मेरी बहन को खेत में खींचकर उसके साथ गलत किया", "मेरी पत्नी की इज्जत लूटी",
                        "मेरी नाबालिग बेटी के साथ दुष्कर्म किया", "मेरे कपड़े फाड़े और गलत काम किया",
                        "मेरी भतीजी के साथ सामूहिक दुष्कर्म किया"],
                "when": ["कल रात", "खेत जाते समय", "काम से लौटते हुए", "दो दिन पहले",
                         "जब घर पर कोई नहीं था", "अंधेरा होने के बाद"],
                "extra": ["तब से वो रो रही है", "उन्होंने वीडियो बना लिया है और धमका रहे हैं",
                          "अभी पुलिस को नहीं बताया", "उसे डॉक्टर की जरूरत है"],
            },
            "patterns": [
                "{who} {when} {act}", "{when} {who} {act}", "{who} {act} और {extra}",
                "कैसे बताऊं समझ नहीं आता, {who} {act}",
            ],
        },
        "gu": {
            "slots": {
                "who": ["ગામના ત્રણ લોકોએ", "માલિકના દીકરાએ", "કોન્ટ્રાક્ટરે", "બે અજાણ્યા માણસોએ",
                        "ઊંચી જાતિના છોકરાઓએ"],
                "act": ["મારી દીકરી પર બળાત્કાર કર્યો", "મારી સાથે જબરદસ્તી કરી",
                        "મારી બહેનને ખેતરમાં ખેંચીને ખોટું કર્યું", "મારી પત્નીની આબરૂ લૂંટી",
                        "મારી સગીર દીકરી પર દુષ્કર્મ કર્યું"],
                "when": ["ગઈ રાત્રે", "ખેતરે જતી વખતે", "કામેથી પાછા આવતા", "બે દિવસ પહેલા",
                         "જ્યારે ઘરે કોઈ નહોતું"],
                "extra": ["ત્યારથી એ રડ્યા કરે છે", "એમણે વિડિયો બનાવી લીધો છે", "હજી પોલીસને કહ્યું નથી",
                          "એને ડોક્ટરની જરૂર છે"],
            },
            "patterns": ["{who} {when} {act}", "{when} {who} {act}", "{who} {act} અને {extra}"],
        },
        "rom": {
            "slots": {
                "who": ["gaon ke teen logo ne", "malik ke bete ne", "thekedar ne", "do anjaan aadmiyo ne",
                        "unchi jaati ke ladko ne", "gam na tran loko e"],
                "act": ["meri beti ke saath balatkar kiya", "mere saath zabardasti ki",
                        "meri behen ko khet me kheench kar galat kiya", "meri patni ki izzat looti",
                        "meri beti ke saath dushkarm kiya", "mari dikri par balatkar karyo"],
                "when": ["kal raat", "khet jaate samay", "kaam se lautte hue", "do din pehle",
                         "jab ghar pe koi nahi tha"],
                "extra": ["tab se wo ro rahi hai", "unhone video bana liya hai", "abhi police ko nahi bataya",
                          "use doctor ki zarurat hai"],
            },
            "patterns": ["{who} {when} {act}", "{when} {who} {act}", "{who} {act} aur {extra}"],
        },
    },
    # ----------------------------------------------------------------
    "family_murder": {
        "en": {
            "slots": {
                "victim": ["my father", "my brother", "my son", "my husband", "my uncle", "my cousin", "my mother"],
                "how": ["was killed by", "was murdered by", "was burnt to death by", "was hacked with an axe by",
                        "was shot dead by", "was lynched by", "did not survive the attack by"],
                "who": ["the upper caste men", "the landlord's people", "men from the village",
                        "the sarpanch's gang", "the people we had a land dispute with"],
                "when": ["last month", "three days ago", "in front of our house", "during the fight over the land",
                         "after he filed the complaint", "last year"],
                "extra": ["we still have not got the body back", "the killers are roaming free",
                          "we are scared we will be next", "my mother has stopped eating",
                          "nobody has been arrested"],
            },
            "patterns": [
                "{victim} {how} {who} {when}", "{when} {victim} {how} {who}",
                "{victim} {how} {who} and {extra}", "{extra}, {victim} {how} {who}",
                "i still cannot believe {victim} {how} {who}",
            ],
        },
        "hi": {
            "slots": {
                "victim": ["मेरे पिता", "मेरे भाई", "मेरे बेटे", "मेरे पति", "मेरे चाचा"],
                "how": ["की हत्या कर दी", "को जान से मार डाला", "को जिंदा जला दिया", "को कुल्हाड़ी से काट डाला",
                        "को गोली मार दी", "को पीट पीट कर मार डाला"],
                "who": ["ऊंची जाति के लोगों", "मालिक के आदमियों", "गांव के लोगों", "सरपंच के गुंडों",
                        "जमीन के विवाद वाले लोगों"],
                "when": ["पिछले महीने", "तीन दिन पहले", "हमारे घर के सामने", "जमीन के झगड़े में",
                         "शिकायत करने के बाद"],
                "extra": ["हत्यारे खुले घूम रहे हैं", "डर है कि अगला नंबर हमारा है", "मां ने खाना छोड़ दिया है",
                          "किसी की गिरफ्तारी नहीं हुई"],
            },
            "patterns": [
                "{who} ने {when} {victim} {how}", "{when} {who} ने {victim} {how}",
                "{who} ने {victim} {how} और {extra}",
            ],
        },
        "gu": {
            "slots": {
                "victim": ["મારા પપ્પા", "મારા ભાઈ", "મારા દીકરા", "મારા પતિ"],
                "how": ["ની હત્યા કરી નાખી", "ને મારી નાખ્યા", "ને જીવતા સળગાવી દીધા", "ને ગોળી મારી દીધી"],
                "who": ["ઊંચી જાતિના લોકો", "માલિકના માણસો", "ગામના લોકો", "સરપંચના ગુંડા"],
                "when": ["ગયા મહિને", "ત્રણ દિવસ પહેલા", "અમારા ઘર સામે", "જમીનના ઝઘડામાં"],
                "extra": ["હત્યારા ખુલ્લા ફરે છે", "ડર છે કે હવે અમારો વારો છે", "કોઈની ધરપકડ નથી થઈ"],
            },
            "patterns": ["{who}એ {when} {victim} {how}", "{when} {who}એ {victim} {how}",
                         "{who}એ {victim} {how} અને {extra}"],
        },
        "rom": {
            "slots": {
                "victim": ["mere papa", "mere bhai", "mere bete", "mere pati", "mara papa"],
                "how": ["ki hatya kar di", "ko jaan se maar dala", "ko zinda jala diya", "ko goli maar di",
                        "ko peet peet kar maar dala", "ne mari nakhya"],
                "who": ["unchi jaati ke logo", "malik ke aadmiyo", "gaon ke logo", "sarpanch ke gundo"],
                "when": ["pichle mahine", "teen din pehle", "ghar ke saamne", "zameen ke jhagde me"],
                "extra": ["hatyare khule ghoom rahe hai", "dar hai agla number hamara hai",
                          "kisi ki giraftari nahi hui"],
            },
            "patterns": ["{who} ne {when} {victim} {how}", "{when} {who} ne {victim} {how}",
                         "{who} ne {victim} {how} aur {extra}"],
        },
    },
    # ----------------------------------------------------------------
    "witness_intimidation": {
        "en": {
            "slots": {
                "who": ["the accused", "their family", "the men who attacked us", "the sarpanch",
                        "their lawyer", "people sent by them"],
                "press": ["keep telling me to withdraw my complaint", "are pressuring me to settle out of court",
                          "came to my house and said to change my statement",
                          "offered money if i stay quiet in court",
                          "said something will happen to my son if i give evidence",
                          "are asking me to turn hostile", "told my family to forget the case",
                          "follow me every time there is a hearing"],
                "when": ["every day", "since they got bail", "before every hearing", "again last night",
                         "since the chargesheet was filed"],
            },
            "patterns": [
                "{who} {press} {when}", "{when} {who} {press}", "the hearing is next week and {who} {press}",
                "{who} {press} and i am scared to go to court",
            ],
        },
        "hi": {
            "slots": {
                "who": ["आरोपी", "उनके घर वाले", "हमला करने वाले लोग", "उनका वकील", "उनके भेजे हुए लोग"],
                "press": ["शिकायत वापस लेने को कह रहे हैं", "कोर्ट के बाहर समझौता करने का दबाव डाल रहे हैं",
                          "घर आकर बयान बदलने को कह गए", "चुप रहने के लिए पैसे दे रहे हैं",
                          "कहते हैं गवाही दी तो बेटे को कुछ हो जाएगा", "मुकर जाने को कह रहे हैं",
                          "हर पेशी पर पीछा करते हैं"],
                "when": ["रोज", "जमानत मिलने के बाद से", "हर पेशी से पहले", "कल रात फिर"],
            },
            "patterns": ["{who} {when} {press}", "अगले हफ्ते पेशी है और {who} {press}",
                         "{who} {press} और मुझे कोर्ट जाने से डर लगता है"],
        },
        "gu": {
            "slots": {
                "who": ["આરોપીઓ", "એમના ઘરવાળા", "હુમલો કરનારા લોકો", "એમનો વકીલ"],
                "press": ["ફરિયાદ પાછી ખેંચવાનું કહે છે", "સમાધાન કરવા દબાણ કરે છે",
                          "ઘરે આવીને નિવેદન બદલવા કહી ગયા", "ચૂપ રહેવા પૈસા આપે છે",
                          "કહે છે જુબાની આપી તો દીકરાને કંઈક થશે"],
                "when": ["રોજ", "જામીન મળ્યા પછીથી", "દરેક મુદત પહેલાં"],
            },
            "patterns": ["{who} {when} {press}", "{who} {press} અને મને કોર્ટ જતા ડર લાગે છે"],
        },
        "rom": {
            "slots": {
                "who": ["aaropi", "unke ghar wale", "hamla karne wale log", "unka vakeel", "aaropi o"],
                "press": ["shikayat wapas lene ko keh rahe hai", "samjhauta karne ka dabav daal rahe hai",
                          "ghar aakar bayan badalne ko keh gaye", "chup rehne ke liye paise de rahe hai",
                          "kehte hai gawahi di to bete ko kuch ho jayega", "mukar jaane ko keh rahe hai",
                          "fariyad pachi khenchvanu kahe chhe"],
                "when": ["roz", "jamanat milne ke baad se", "har peshi se pehle", "kal raat phir"],
            },
            "patterns": ["{who} {when} {press}", "{who} {press} aur mujhe court jaane se dar lagta hai"],
        },
    },
    # ----------------------------------------------------------------
    "social_boycott": {
        "en": {
            "slots": {
                "who": ["the village", "the panchayat", "the upper caste families", "the whole community",
                        "the sarpanch"],
                "act": ["has stopped us from taking water from the common tap",
                        "has told shopkeepers not to sell us anything",
                        "announced that nobody should give us work", "will not let us use the village road",
                        "stopped our children from going to the school",
                        "fined us and threw us out of the community", "has cut us off completely",
                        "told everyone not to speak to our family"],
                "since": ["since we filed the complaint", "for the last two months",
                          "after my son married outside the caste", "since the land case",
                          "ever since the protest"],
            },
            "patterns": ["{who} {act} {since}", "{since} {who} {act}",
                         "{who} {act} and we are struggling to eat", "{who} {act}, we have no one to turn to"],
        },
        "hi": {
            "slots": {
                "who": ["गांव वालों ने", "पंचायत ने", "ऊंची जाति के परिवारों ने", "पूरे समाज ने", "सरपंच ने"],
                "act": ["सरकारी नल से पानी भरना बंद करवा दिया", "दुकानदारों को हमें सामान न देने को कहा",
                        "हमें काम न देने का फरमान सुनाया", "गांव का रास्ता बंद कर दिया",
                        "बच्चों का स्कूल जाना बंद करवा दिया", "जुर्माना लगाकर बिरादरी से निकाल दिया",
                        "हमसे सारे रिश्ते तोड़ लिए", "सबको हमसे बात न करने को कहा"],
                "since": ["जब से शिकायत की है", "पिछले दो महीने से", "बेटे की शादी के बाद से",
                          "जमीन के केस के बाद से"],
            },
            "patterns": ["{since} {who} {act}", "{who} {act} और खाने के भी लाले पड़ गए"],
        },
        "gu": {
            "slots": {
                "who": ["ગામવાળાએ", "પંચાયતે", "ઊંચી જાતિના પરિવારોએ", "આખા સમાજે"],
                "act": ["જાહેર નળ પરથી પાણી ભરવાનું બંધ કરાવ્યું", "દુકાનદારોને અમને સામાન ન આપવા કહ્યું",
                        "અમને કામ ન આપવાનો હુકમ કર્યો", "ગામનો રસ્તો બંધ કરી દીધો",
                        "દંડ કરીને સમાજમાંથી બહાર કર્યા", "બધાને અમારી સાથે વાત ન કરવા કહ્યું"],
                "since": ["ફરિયાદ કરી ત્યારથી", "છેલ્લા બે મહિનાથી", "જમીનના કેસ પછીથી"],
            },
            "patterns": ["{since} {who} {act}", "{who} {act} અને ખાવાના પણ ફાંફા છે"],
        },
        "rom": {
            "slots": {
                "who": ["gaon walo ne", "panchayat ne", "unchi jaati ke parivaro ne", "poore samaj ne",
                        "gam vala e"],
                "act": ["nal se paani bharna band karwa diya", "dukandaaro ko saaman na dene ko kaha",
                        "hume kaam na dene ka farmaan sunaya", "gaon ka raasta band kar diya",
                        "bachho ka school jaana band karwa diya", "jurmana lagakar biradari se nikaal diya",
                        "sabko humse baat na karne ko kaha", "amne kaam na aapvano hukam karyo"],
                "since": ["jab se shikayat ki hai", "pichle do mahine se", "zameen ke case ke baad se"],
            },
            "patterns": ["{since} {who} {act}", "{who} {act} aur khane ke bhi laale pad gaye"],
        },
    },
    # ----------------------------------------------------------------
    "displacement_arson": {
        "en": {
            "slots": {
                "who": ["the upper caste men", "the landlord's goons", "a mob from the next village",
                        "the people who want our land", "the sarpanch's men"],
                "act": ["set fire to our huts", "burnt down our house", "demolished our home with a tractor",
                        "forced all of us out of the village", "occupied the land the government gave us",
                        "destroyed our crops and our shed",
                        "threw our belongings on the road and locked our house"],
                "now": ["and now we are living under a tree", "and we are staying at a relative's place",
                        "and we have nowhere to sleep", "and our papers were burnt too",
                        "and the children have no clothes left"],
                "when": ["last night", "two weeks ago", "during the riot", "after the election",
                         "while we were at work"],
            },
            "patterns": ["{who} {act} {when} {now}", "{when} {who} {act}", "{who} {act} {now}",
                         "we lost everything, {who} {act} {when}"],
        },
        "hi": {
            "slots": {
                "who": ["ऊंची जाति के लोगों ने", "मालिक के गुंडों ने", "बगल के गांव की भीड़ ने",
                        "हमारी जमीन चाहने वालों ने"],
                "act": ["हमारी झोपड़ियों में आग लगा दी", "हमारा घर जला डाला", "ट्रैक्टर से हमारा घर गिरा दिया",
                        "हम सबको गांव से भगा दिया", "सरकार की दी हुई जमीन पर कब्जा कर लिया",
                        "हमारी फसल और छप्पर बर्बाद कर दिए"],
                "now": ["अब हम पेड़ के नीचे रह रहे हैं", "रिश्तेदार के यहां रुके हैं", "सोने की भी जगह नहीं है",
                        "हमारे कागज भी जल गए"],
                "when": ["कल रात", "दो हफ्ते पहले", "चुनाव के बाद", "जब हम काम पर थे"],
            },
            "patterns": ["{who} {when} {act} और {now}", "{when} {who} {act}",
                         "सब कुछ खत्म हो गया, {who} {act}"],
        },
        "gu": {
            "slots": {
                "who": ["ઊંચી જાતિના લોકોએ", "માલિકના ગુંડાઓએ", "બાજુના ગામના ટોળાએ"],
                "act": ["અમારા ઝૂંપડામાં આગ લગાડી દીધી", "અમારું ઘર સળગાવી નાખ્યું",
                        "ટ્રેક્ટરથી અમારું ઘર તોડી પાડ્યું", "અમને બધાને ગામ છોડવા મજબૂર કર્યા",
                        "સરકારે આપેલી જમીન પર કબજો કરી લીધો"],
                "now": ["હવે અમે ઝાડ નીચે રહીએ છીએ", "સગાને ત્યાં રહીએ છીએ", "સૂવાની પણ જગ્યા નથી"],
                "when": ["ગઈ રાત્રે", "બે અઠવાડિયા પહેલા", "ચૂંટણી પછી"],
            },
            "patterns": ["{who} {when} {act} અને {now}", "{when} {who} {act}"],
        },
        "rom": {
            "slots": {
                "who": ["unchi jaati ke logo ne", "malik ke gundo ne", "bagal ke gaon ki bheed ne",
                        "unchi jati na loko e"],
                "act": ["jhopdiyo me aag laga di", "hamara ghar jala dala", "tractor se ghar gira diya",
                        "hum sabko gaon se bhaga diya", "sarkari zameen par kabza kar liya",
                        "fasal barbaad kar di", "amaru ghar salgavi nakhyu"],
                "now": ["ab hum ped ke neeche reh rahe hai", "rishtedar ke yaha ruke hai",
                        "sone ki bhi jagah nahi hai"],
                "when": ["kal raat", "do hafte pehle", "chunav ke baad"],
            },
            "patterns": ["{who} {when} {act} aur {now}", "{when} {who} {act}"],
        },
    },
    # ----------------------------------------------------------------
    "police_noncooperation": {
        "en": {
            "slots": {
                "who": ["the police", "the station officer", "the constable", "the sho",
                        "the investigating officer", "the police at our thana"],
                "act": ["refused to write down my complaint", "asked for money before they would file the case",
                        "told me to go home and sort it out with them",
                        "registered a lighter section instead of the atrocity act",
                        "have not arrested anyone even after a month", "keep delaying the chargesheet",
                        "made fun of me when i went to complain",
                        "sent me away saying it is a family matter", "are friendly with the accused",
                        "tore up my written application"],
                "when": ["three times now", "every time i go", "for six months", "even after the medical report",
                         "since the incident"],
            },
            "patterns": ["{who} {act}", "{who} {act} {when}", "{when} {who} {act}",
                         "i went to report it but {who} {act}",
                         "{who} {act} and i do not know where else to go"],
        },
        "hi": {
            "slots": {
                "who": ["पुलिस ने", "थानेदार ने", "सिपाही ने", "जांच अधिकारी ने"],
                "act": ["मेरी शिकायत लिखने से इनकार कर दिया", "केस दर्ज करने के लिए पैसे मांगे",
                        "घर जाकर आपस में निपटाने को कहा", "एट्रोसिटी एक्ट की धारा नहीं लगाई",
                        "महीने भर में किसी को गिरफ्तार नहीं किया", "मेरा मजाक उड़ाया",
                        "घरेलू मामला कहकर भगा दिया", "मेरी अर्जी फाड़ दी"],
                "when": ["तीन बार", "हर बार", "छह महीने से"],
            },
            "patterns": ["{who} {act}", "{who} {when} {act}", "मैं रिपोर्ट करने गई पर {who} {act}"],
        },
        "gu": {
            "slots": {
                "who": ["પોલીસે", "થાણેદારે", "કોન્સ્ટેબલે", "તપાસ અધિકારીએ"],
                "act": ["મારી ફરિયાદ લખવાની ના પાડી", "કેસ નોંધવા પૈસા માંગ્યા",
                        "ઘરે જઈને સમાધાન કરવાનું કહ્યું", "એટ્રોસિટીની કલમ ન લગાડી",
                        "કોઈની ધરપકડ ન કરી", "ઘરેલુ મામલો કહીને પાછા મોકલી દીધા"],
                "when": ["ત્રણ વાર", "દર વખતે", "છ મહિનાથી"],
            },
            "patterns": ["{who} {act}", "{who} {when} {act}", "હું ફરિયાદ કરવા ગઈ પણ {who} {act}"],
        },
        "rom": {
            "slots": {
                "who": ["police ne", "thanedar ne", "sipahi ne", "jaanch adhikari ne", "police e"],
                "act": ["meri shikayat likhne se mana kar diya", "case darj karne ke liye paise maange",
                        "ghar jaakar aapas me niptane ko kaha", "atrocity act ki dhara nahi lagayi",
                        "mahine bhar me kisi ko giraftar nahi kiya", "mera mazak udaya",
                        "gharelu mamla keh kar bhaga diya", "fariyad lakhvani na padi"],
                "when": ["teen baar", "har baar", "chhe mahine se"],
            },
            "patterns": ["{who} {act}", "{who} {when} {act}", "main report karne gayi par {who} {act}"],
        },
    },
}


# Hard negatives: harmless messages that share words with the harm
# categories (police, pending, temple, tomorrow, tired, fire, court,
# village, school...). Round 19's first training run escalated several
# messages like these because character n-grams alone cannot tell
# "scraped" from "raped" or a kitchen fire from arson. Adding them to the
# negative class is what teaches the model the difference.
HARD_NEGATIVES = {
    "en": [
        "the police were very helpful and registered my case the same day",
        "my passport application is still pending with the office",
        "my board exam result is pending, i am a little nervous",
        "we went to the temple for the festival and it was lovely",
        "my brother will call me tomorrow about the wedding plans",
        "he said he will come on monday to repair the tap",
        "i fell off my cycle and scraped my elbow, it is fine now",
        "she draped the saree beautifully for the function",
        "we bought grapes and bananas from the market",
        "this summer heat is killing me, i cannot sleep well",
        "i am tired after the night shift but otherwise okay",
        "exams are stressful but my family is supportive",
        "the court date for my land mutation is next month",
        "the village panchayat is building a new road, we are happy",
        "our school has started a free lunch programme",
        "there was a small kitchen fire but everyone is safe and it was put out",
        "my father retired from the railways last year",
        "the constable came to verify my address for the job",
        "my cousin is joining the police force next month",
        "we are shifting to a new house because my job changed",
        "my son hit a six in the cricket match today",
        "the teacher asked the children to sit in rows for the exam",
        "i need a copy of my caste certificate for the college form",
        "the sarpanch invited everyone to the gram sabha meeting",
        "the landlord fixed the roof before the monsoon",
        "i want to thank the counsellor, i feel much better now",
        "my daughter got admission in the hostel, we are very proud",
        "the water supply in our area comes at six in the morning",
        "our goat gave birth to two kids this morning",
        "the doctor said my mother's operation went well",
        "i am calling to ask about the bank loan for my shop",
        "the officer explained the scheme very clearly",
        "my phone was stolen at the bus stand, i need to block the sim",
        "i missed the bus and had to walk home, very tiring day",
        "the neighbours helped us during the flood",
        "can the relief cheque be deposited directly in my account",
    ],
    "hi": [
        "पुलिस ने बहुत मदद की और उसी दिन केस दर्ज कर लिया",
        "मेरा पासपोर्ट का आवेदन अभी पेंडिंग है",
        "बोर्ड परीक्षा का रिजल्ट अभी आना बाकी है",
        "हम त्योहार पर मंदिर गए, बहुत अच्छा लगा",
        "भाई कल शादी की तैयारी के बारे में फोन करेगा",
        "साइकिल से गिरकर कोहनी छिल गई, अब ठीक है",
        "गर्मी बहुत है, रात को ठीक से नींद नहीं आती",
        "रात की ड्यूटी के बाद थकान है बाकी सब ठीक",
        "जमीन के दाखिल खारिज की तारीख अगले महीने है",
        "पंचायत नई सड़क बना रही है, हम खुश हैं",
        "रसोई में छोटी सी आग लगी थी पर सब सुरक्षित हैं",
        "कॉलेज के फॉर्म के लिए जाति प्रमाण पत्र की कॉपी चाहिए",
        "बेटी को हॉस्टल में दाखिला मिल गया",
        "डॉक्टर ने कहा मां का ऑपरेशन ठीक हो गया",
        "बस अड्डे पर फोन चोरी हो गया, सिम बंद करवानी है",
        "सिपाही नौकरी के लिए पता सत्यापन करने आया था",
    ],
    "gu": [
        "પોલીસે ખૂબ મદદ કરી અને એ જ દિવસે કેસ નોંધી લીધો",
        "મારી પાસપોર્ટની અરજી હજી બાકી છે",
        "અમે તહેવારમાં મંદિરે ગયા, ખૂબ મજા આવી",
        "ભાઈ કાલે લગ્નની તૈયારી વિશે ફોન કરશે",
        "સાયકલ પરથી પડી જતા કોણી છોલાઈ ગઈ, હવે સારું છે",
        "રાતની નોકરી પછી થાક છે બાકી બધું બરાબર",
        "જમીનની નોંધની તારીખ આવતા મહિને છે",
        "રસોડામાં નાની આગ લાગી હતી પણ બધા સલામત છે",
        "કોલેજના ફોર્મ માટે જાતિના દાખલાની નકલ જોઈએ",
        "દીકરીને હોસ્ટેલમાં પ્રવેશ મળી ગયો",
    ],
    "rom": [
        "police ne bahut madad ki aur usi din case darj kar liya",
        "mera passport ka application abhi pending hai",
        "hum tyohar pe mandir gaye bahut accha laga",
        "bhai kal shaadi ki taiyari ke baare me phone karega",
        "cycle se gir kar kohni chhil gayi ab theek hai",
        "garmi bahut hai raat ko neend nahi aati theek se",
        "raat ki duty ke baad thakan hai baaki sab theek",
        "rasoi me chhoti si aag lagi thi par sab safe hai",
        "college form ke liye caste certificate ki copy chahiye",
        "beti ko hostel me admission mil gaya",
        "police e khub madad kari ane case nondhi lidho",
        "mandir e gaya hata tahevar ma maja aavi",
    ],
}
