"""
Compositional expression templates — the bulk of the training corpus.

WHY THIS EXISTS ALONGSIDE expressions.py
----------------------------------------
`expressions.py` holds hand-written, idiomatic disclosures. They are
valuable (they are the hard, indirect cases) but there are only ~15 per
category per language, and that turned out to be the wrong shape for
training: holding a quarter of them out produced test sentences with
almost no vocabulary in common with the training ones, and recall
collapsed to ~0.24 micro. That is not a fair test of any bag-of-words
model, and it is not how language works either — real disclosures of
the same thing reuse the same words in different arrangements.

So the bulk of the corpus is generated here instead, from per-category
slot vocabularies and sentence patterns. Filling "{who} {hit} me
{when}" across actors, verbs and time expressions yields hundreds of
distinct sentences per category that share vocabulary while differing
in surface form. Holding out whole generated sentences then measures
the thing worth measuring: can the model recognise a disclosure whose
exact wording it has never seen, built from language it has?

This is deliberately a weaker claim than "the model understands
distress". It does not. What it does is generalise across the
arrangements of words a phrase list has to enumerate one by one — and
that is the specific failure `lexicon.py` documents in its own
docstring.

Slot conventions:
  who    — the person causing harm, as callers refer to them
  when   — time expression
  where  — location / setting
Every string is first person unless the pattern says otherwise.
"""

TEMPLATES = {
    # ----------------------------------------------------------------
    "physical_safety_abuse": {
        "en": {
            "slots": {
                "who": ["he", "my husband", "my brother", "my father", "my partner",
                        "my brother in law", "my son", "my father in law", "the man i live with"],
                "hit": ["hits me", "beats me", "slaps me", "punches me", "kicks me",
                        "shoves me", "pushes me hard", "throws things at me",
                        "drags me by the arm", "grabs me by the hair", "hurts me"],
                "when": ["almost every week", "last night", "again yesterday", "whenever he is angry",
                         "three times this month", "after an argument", "in front of the children",
                         "when nobody else is home", "every few days", "since the wedding"],
                "mark": ["bruises on my arm", "marks on my back", "a swollen lip",
                         "a cut on my forehead", "pain in my shoulder for days",
                         "a mark i have to cover up"],
            },
            "patterns": [
                "{who} {hit} {when}",
                "{when} {who} {hit}",
                "{who} {hit} and i have {mark}",
                "i have {mark} because {who} {hit} {when}",
                "it has got worse, now {who} {hit} {when}",
                "{who} {hit} and nobody in the house says anything",
                "i did not want to say this but {who} {hit} {when}",
                "there are {mark} from when {who} {hit}",
                "{who} {hit} {when} and i have nowhere to go",
            ],
        },
        "hi": {
            "slots": {
                "who": ["वो", "मेरे पति", "मेरा भाई", "मेरे पिता", "मेरा देवर",
                        "मेरा बेटा", "मेरे ससुर", "जिसके साथ मैं रहती हूं वो"],
                "hit": ["मुझे मारता है", "मुझे पीटता है", "थप्पड़ मारता है", "लात मारता है",
                        "धक्का देता है", "चीजें फेंक कर मारता है", "बाल पकड़कर खींचता है",
                        "हाथ पकड़कर घसीटता है", "मुझे चोट पहुंचाता है",
                        "मुझ पर हाथ उठाता है", "मुझ पर हाथ छोड़ता है",
                        "मारपीट करता है", "पीट पीट कर मारता है"],
                "when": ["लगभग हर हफ्ते", "कल रात", "कल फिर", "जब भी गुस्सा आता है",
                         "इस महीने तीन बार", "झगड़े के बाद", "बच्चों के सामने",
                         "जब घर में कोई नहीं होता", "शादी के बाद से"],
                "mark": ["बांह पर नील", "पीठ पर निशान", "सूजा हुआ होंठ",
                         "माथे पर चोट", "कई दिन तक कंधे में दर्द"],
            },
            "patterns": [
                "{who} {when} {hit}",
                "{when} {who} {hit}",
                "{who} {hit} और मेरे {mark} हैं",
                "मेरे {mark} हैं क्योंकि {who} {when} {hit}",
                "अब हालत और बिगड़ गई है, {who} {when} {hit}",
                "{who} {hit} और घर में कोई कुछ नहीं कहता",
                "बताना नहीं चाहती थी पर {who} {when} {hit}",
                "{who} {when} {hit} और मेरे पास जाने की कोई जगह नहीं",
            ],
        },
        "gu": {
            "slots": {
                "who": ["એ", "મારા પતિ", "મારો ભાઈ", "મારા પપ્પા", "મારો દિયર",
                        "મારો દીકરો", "મારા સસરા"],
                "hit": ["મને મારે છે", "મને પીટે છે", "થપ્પડ મારે છે", "લાત મારે છે",
                        "ધક્કો મારે છે", "વસ્તુઓ ફેંકીને મારે છે", "વાળ પકડીને ખેંચે છે",
                        "હાથ પકડીને ઘસડે છે", "મારા પર હાથ ઉપાડે છે",
                        "મારપીટ કરે છે", "મને ખૂબ મારે છે"],
                "when": ["લગભગ દર અઠવાડિયે", "ગઈ રાત્રે", "ગઈ કાલે ફરી", "જ્યારે પણ ગુસ્સો આવે",
                         "આ મહિને ત્રણ વાર", "ઝઘડા પછી", "બાળકો સામે",
                         "જ્યારે ઘરમાં કોઈ ન હોય", "લગ્ન પછીથી"],
                "mark": ["હાથ પર નિશાન", "પીઠ પર ડાઘ", "સૂજેલો હોઠ", "કપાળ પર વાગ્યું"],
            },
            "patterns": [
                "{who} {when} {hit}",
                "{when} {who} {hit}",
                "{who} {hit} અને મારા {mark} છે",
                "મારા {mark} છે કારણ કે {who} {when} {hit}",
                "હવે વધારે બગડ્યું છે, {who} {when} {hit}",
                "{who} {hit} અને ઘરમાં કોઈ કંઈ કહેતું નથી",
                "{who} {when} {hit} અને મારે જવાની કોઈ જગ્યા નથી",
            ],
        },
        "rom": {
            "slots": {
                "who": ["wo", "mere pati", "mera bhai", "mere papa", "mera devar",
                        "mera beta", "mere sasur", "mara pati", "maro bhai"],
                "hit": ["mujhe marta hai", "mujhe peetta hai", "thappad marta hai", "laat marta hai",
                        "dhakka deta hai", "cheezein fenk kar marta hai", "baal pakad kar kheenchta hai",
                        "haath pakad kar ghaseetta hai", "mane mare chhe", "mane pite chhe",
                        "mujh par haath uthata hai", "mujh par haath chhodta hai",
                        "marpeet karta hai", "mara par haath upade chhe"],
                "when": ["lagbhag har hafte", "kal raat", "kal phir", "jab bhi gussa aata hai",
                         "is mahine teen baar", "jhagde ke baad", "bachho ke saamne",
                         "jab ghar me koi nahi hota", "shaadi ke baad se", "dar athvadiye"],
                "mark": ["baanh par neel", "peeth par nishan", "sooja hua hoth",
                         "mathe par chot", "kandhe me kai din dard"],
            },
            "patterns": [
                "{who} {when} {hit}",
                "{when} {who} {hit}",
                "{who} {hit} aur mere {mark} hai",
                "mere {mark} hai kyunki {who} {when} {hit}",
                "ab aur bigad gaya hai, {who} {when} {hit}",
                "{who} {hit} aur ghar me koi kuch nahi kehta",
                "batana nahi chahti thi par {who} {when} {hit}",
                "{who} {when} {hit} aur mere paas jane ki koi jagah nahi",
            ],
        },
    },
    # ----------------------------------------------------------------
    "suicidal_ideation": {
        "en": {
            "slots": {
                "verb": ["want to end my life", "think about killing myself",
                         "want to die", "think about ending it all",
                         "wish i was dead", "want to stop living",
                         "keep thinking about taking my own life",
                         "have thought about finishing myself"],
                "freq": ["every night", "all the time now", "more and more often",
                         "for the last two months", "since it started", "most days",
                         "when the house is quiet", "whenever i am alone"],
                "extra": ["i have nothing left", "nobody would miss me",
                          "i cannot see any other way out", "i am so tired of all of this",
                          "i have already worked out how", "i have written it down",
                          "i do not want to wake up tomorrow"],
            },
            "patterns": [
                "i {verb} {freq}",
                "{freq} i {verb}",
                "i {verb} and {extra}",
                "{extra}, i {verb} {freq}",
                "honestly i {verb} {freq}",
                "i have not told anyone this but i {verb} {freq}",
                "i {verb}, {extra}",
            ],
        },
        "hi": {
            "slots": {
                "verb": ["अपनी जान देना चाहती हूं", "खुद को खत्म करने की सोचती हूं",
                         "मरना चाहती हूं", "सब खत्म करने का सोचती हूं",
                         "जीना नहीं चाहती", "अपनी जिंदगी खत्म करने का सोचता हूं",
                         "जीने का मन नहीं करता", "जिंदा रहने का मन नहीं करता",
                         "जीने की इच्छा नहीं रही", "मरने का खयाल आता है",
                         "अब सांस लेना भी बोझ लगता है"],
                "freq": ["हर रात", "अब हर वक्त", "दिन ब दिन ज्यादा", "पिछले दो महीने से",
                         "जब से यह शुरू हुआ", "ज्यादातर दिन", "जब घर में सन्नाटा होता है",
                         "जब भी अकेली होती हूं"],
                "extra": ["मेरे पास कुछ नहीं बचा", "मेरी कोई याद भी नहीं करेगा",
                          "कोई और रास्ता नहीं दिखता", "मैं इस सबसे बहुत थक गई हूं",
                          "मैंने तरीका भी सोच लिया है", "कल सुबह उठने का मन नहीं"],
            },
            "patterns": [
                "मैं {freq} {verb}",
                "{freq} मैं {verb}",
                "मैं {verb} और {extra}",
                "{extra}, मैं {freq} {verb}",
                "सच कहूं तो मैं {freq} {verb}",
                "यह किसी को नहीं बताया पर मैं {freq} {verb}",
            ],
        },
        "gu": {
            "slots": {
                "verb": ["મારો જીવ આપી દેવા માંગું છું", "મારી જાતને ખતમ કરવાનું વિચારું છું",
                         "મરવા માંગું છું", "બધું પતાવી દેવાનું વિચારું છું",
                         "જીવવા નથી માંગતી", "જીવવાનું મન નથી થતું",
                         "જીવવાની ઈચ્છા રહી નથી", "મરવાનો વિચાર આવે છે",
                         "હવે શ્વાસ લેવો પણ બોજ લાગે છે"],
                "freq": ["દર રાત્રે", "હવે દરેક વખતે", "દિવસે દિવસે વધારે", "છેલ્લા બે મહિનાથી",
                         "જ્યારથી આ શરૂ થયું", "મોટાભાગના દિવસો", "જ્યારે પણ એકલી હોઉં"],
                "extra": ["મારી પાસે કંઈ બચ્યું નથી", "મને કોઈ યાદ પણ નહીં કરે",
                          "બીજો કોઈ રસ્તો દેખાતો નથી", "હું આ બધાથી થાકી ગઈ છું",
                          "મેં રીત પણ વિચારી લીધી છે"],
            },
            "patterns": [
                "હું {freq} {verb}",
                "{freq} હું {verb}",
                "હું {verb} અને {extra}",
                "{extra}, હું {freq} {verb}",
                "સાચું કહું તો હું {freq} {verb}",
            ],
        },
        "rom": {
            "slots": {
                "verb": ["apni jaan dena chahti hu", "khud ko khatam karne ki sochti hu",
                         "marna chahti hu", "sab khatam karne ka sochti hu",
                         "jeena nahi chahti", "apni zindagi khatam karne ka sochta hu",
                         "marva mangu chhu", "jivva nathi mangti",
                         "jeene ka mann nahi karta", "zinda rehne ka mann nahi karta",
                         "jeene ki ichha nahi rahi", "marne ka khayal aata hai",
                         "khud ko mar dalne ka mann karta hai", "jeene se dar lagta hai",
                         "ab saans lena bhi bojh lagta hai"],
                "freq": ["har raat", "ab har waqt", "din b din zyada", "pichle do mahine se",
                         "jab se yeh shuru hua", "zyadatar din", "jab bhi akeli hoti hu",
                         "dar raatre"],
                "extra": ["mere paas kuch nahi bacha", "meri koi yaad bhi nahi karega",
                          "koi aur rasta nahi dikhta", "main is sab se bahut thak gayi hu",
                          "maine tarika bhi soch liya hai", "kal subah uthne ka mann nahi"],
            },
            "patterns": [
                "main {freq} {verb}",
                "{freq} main {verb}",
                "main {verb} aur {extra}",
                "{extra}, main {freq} {verb}",
                "sach kahu to main {freq} {verb}",
                "yeh kisi ko nahi bataya par main {freq} {verb}",
            ],
        },
    },
    # ----------------------------------------------------------------
    "immediate_danger": {
        "en": {
            "slots": {
                "who": ["he", "my husband", "he and his brother", "the man"],
                "now": ["is right outside the door", "is in the next room",
                        "is coming up the stairs", "is banging on the door",
                        "has just come home drunk", "is looking for me right now",
                        "will not let me out of the house", "is holding a knife",
                        "is standing behind me", "has locked me in"],
                "state": ["i am hiding in the bathroom", "i am whispering so he does not hear",
                          "i have only a minute", "i am bleeding", "please send someone now",
                          "i do not know what he will do", "i cannot get to the door"],
            },
            "patterns": [
                "{who} {now}, {state}",
                "{state}, {who} {now}",
                "{who} {now} right now",
                "please be quick, {who} {now}",
                "{who} {now} and {state}",
                "i need help now, {who} {now}",
            ],
        },
        "hi": {
            "slots": {
                "who": ["वो", "मेरे पति", "वो और उसका भाई", "वो आदमी"],
                "now": ["अभी दरवाजे के बाहर है", "बगल के कमरे में है",
                        "सीढ़ियों से ऊपर आ रहा है", "दरवाजा पीट रहा है",
                        "अभी शराब पीकर आया है", "अभी मुझे ढूंढ रहा है",
                        "मुझे घर से निकलने नहीं दे रहा", "हाथ में चाकू लिए है",
                        "मेरे पीछे खड़ा है", "मुझे अंदर बंद कर दिया है"],
                "state": ["मैं बाथरूम में छिपी हूं", "धीरे बोल रही हूं ताकि वो न सुने",
                          "मेरे पास बस एक मिनट है", "मुझे खून बह रहा है", "अभी किसी को भेजिए",
                          "पता नहीं वो क्या करेगा", "मैं दरवाजे तक नहीं पहुंच सकती"],
            },
            "patterns": [
                "{who} {now}, {state}",
                "{state}, {who} {now}",
                "{who} अभी {now}",
                "जल्दी कीजिए, {who} {now}",
                "{who} {now} और {state}",
                "मुझे अभी मदद चाहिए, {who} {now}",
            ],
        },
        "gu": {
            "slots": {
                "who": ["એ", "મારા પતિ", "એ અને એનો ભાઈ", "પેલો માણસ"],
                "now": ["અત્યારે બારણા બહાર છે", "બાજુના રૂમમાં છે",
                        "દાદર ચઢીને આવે છે", "બારણું ધમધમાવે છે",
                        "હમણાં દારૂ પીને આવ્યો છે", "અત્યારે મને શોધે છે",
                        "મને ઘરની બહાર જવા દેતો નથી", "હાથમાં છરી લીધી છે",
                        "મારી પાછળ ઊભો છે", "મને અંદર પૂરી દીધી છે"],
                "state": ["હું બાથરૂમમાં સંતાઈ છું", "ધીમેથી બોલું છું જેથી એ ન સાંભળે",
                          "મારી પાસે એક જ મિનિટ છે", "મને લોહી નીકળે છે", "અત્યારે કોઈને મોકલો",
                          "ખબર નથી એ શું કરશે"],
            },
            "patterns": [
                "{who} {now}, {state}",
                "{state}, {who} {now}",
                "{who} અત્યારે {now}",
                "જલદી કરો, {who} {now}",
                "{who} {now} અને {state}",
            ],
        },
        "rom": {
            "slots": {
                "who": ["wo", "mere pati", "wo aur uska bhai", "wo aadmi", "e"],
                "now": ["abhi darwaze ke bahar hai", "bagal ke room me hai",
                        "seedhi se upar aa raha hai", "darwaza peet raha hai",
                        "abhi sharab peekar aaya hai", "abhi mujhe dhoondh raha hai",
                        "mujhe ghar se nikalne nahi de raha", "haath me chaku liye hai",
                        "mere peeche khada hai", "mujhe andar band kar diya hai"],
                "state": ["main bathroom me chhupi hu", "dheere bol rahi hu taki wo na sune",
                          "mere paas bas ek minute hai", "mujhe khoon beh raha hai",
                          "abhi kisi ko bhejiye", "pata nahi wo kya karega"],
            },
            "patterns": [
                "{who} {now}, {state}",
                "{state}, {who} {now}",
                "{who} abhi {now}",
                "jaldi kijiye, {who} {now}",
                "{who} {now} aur {state}",
                "mujhe abhi madad chahiye, {who} {now}",
            ],
        },
    },
    # ----------------------------------------------------------------
    "sexual_harassment_assault": {
        "en": {
            "slots": {
                "who": ["my manager", "my supervisor", "a colleague", "my landlord",
                        "my husband", "my cousin", "a man in my building",
                        "my teacher", "the shop owner", "my father in law"],
                "act": ["touches me without my permission", "keeps putting his hand on me",
                        "forced himself on me", "made me do things i did not agree to",
                        "makes sexual comments about me", "sends me obscene messages",
                        "tried to pull me into a room", "does not stop when i say no",
                        "touched me inappropriately", "exposed himself to me"],
                "when": ["whenever we are alone", "at work almost daily", "at night",
                         "for the last six months", "every time i go there",
                         "when there is nobody around", "since i started this job"],
                "extra": ["i was too frightened to shout", "i have not told my family",
                          "he says nobody will believe me", "i need this job so i stayed quiet",
                          "i froze and could not move"],
            },
            "patterns": [
                "{who} {act} {when}",
                "{when} {who} {act}",
                "{who} {act} and {extra}",
                "{extra}, {who} {act} {when}",
                "i have to tell someone — {who} {act} {when}",
                "{who} {act}, i did not consent to any of it",
            ],
        },
        "hi": {
            "slots": {
                "who": ["मेरा मैनेजर", "मेरा सुपरवाइजर", "एक सहकर्मी", "मकान मालिक",
                        "मेरे पति", "मेरा चचेरा भाई", "बिल्डिंग में एक आदमी",
                        "मेरे ससुर", "दुकान वाला"],
                "act": ["बिना इजाजत मुझे छूता है", "बार बार मुझ पर हाथ रखता है",
                        "मेरे साथ जबरदस्ती की", "ऐसी चीजें करवाईं जिनके लिए मैंने हां नहीं कही",
                        "मेरे बारे में गंदी बातें करता है", "अश्लील संदेश भेजता है",
                        "कमरे में खींचने की कोशिश की", "मना करने पर भी नहीं रुकता",
                        "गलत तरीके से छुआ"],
                "when": ["जब भी हम अकेले होते हैं", "काम पर लगभग रोज", "रात में",
                         "पिछले छह महीने से", "हर बार जब मैं वहां जाती हूं",
                         "जब आसपास कोई नहीं होता", "जब से यह नौकरी शुरू की"],
                "extra": ["मैं डर के मारे चिल्ला भी नहीं पाई", "घरवालों को नहीं बताया",
                          "कहता है कोई यकीन नहीं करेगा", "नौकरी की जरूरत है इसलिए चुप रही",
                          "मैं जड़ हो गई, हिल भी नहीं पाई"],
            },
            "patterns": [
                "{who} {when} {act}",
                "{when} {who} {act}",
                "{who} {act} और {extra}",
                "{extra}, {who} {when} {act}",
                "किसी को बताना जरूरी है — {who} {when} {act}",
            ],
        },
        "gu": {
            "slots": {
                "who": ["મારો મેનેજર", "મારો સુપરવાઈઝર", "એક સહકર્મી", "મકાનમાલિક",
                        "મારા પતિ", "મારો પિતરાઈ ભાઈ", "બિલ્ડિંગનો એક માણસ", "મારા સસરા"],
                "act": ["પરવાનગી વગર મને અડે છે", "વારંવાર મારા પર હાથ મૂકે છે",
                        "મારી સાથે જબરદસ્તી કરી", "એવું કરાવ્યું જેની મેં હા નથી પાડી",
                        "મારા વિશે ગંદી વાતો કરે છે", "અશ્લીલ મેસેજ મોકલે છે",
                        "રૂમમાં ખેંચવાની કોશિશ કરી", "ના પાડું તોય અટકતો નથી"],
                "when": ["જ્યારે પણ અમે એકલા હોઈએ", "કામ પર લગભગ રોજ", "રાત્રે",
                         "છેલ્લા છ મહિનાથી", "દર વખતે જ્યારે હું ત્યાં જાઉં",
                         "જ્યારે આસપાસ કોઈ ન હોય"],
                "extra": ["હું ડરથી બૂમ પણ ન પાડી શકી", "ઘરવાળાને કહ્યું નથી",
                          "કહે છે કોઈ માનશે નહીં", "નોકરીની જરૂર છે એટલે ચૂપ રહી"],
            },
            "patterns": [
                "{who} {when} {act}",
                "{when} {who} {act}",
                "{who} {act} અને {extra}",
                "{extra}, {who} {when} {act}",
            ],
        },
        "rom": {
            "slots": {
                "who": ["mera manager", "mera supervisor", "ek colleague", "makaan malik",
                        "mere pati", "mera chachera bhai", "building me ek aadmi",
                        "mere sasur", "dukaan wala", "maro manager"],
                "act": ["bina ijazat mujhe chhuta hai", "baar baar mujh par haath rakhta hai",
                        "mere saath zabardasti ki", "aisi cheezein karwayi jinke liye maine haan nahi kahi",
                        "mere baare me gandi baatein karta hai", "ashleel message bhejta hai",
                        "room me kheenchne ki koshish ki", "mana karne par bhi nahi rukta",
                        "galat tarike se chhua"],
                "when": ["jab bhi hum akele hote hain", "kaam par lagbhag roz", "raat me",
                         "pichle chhe mahine se", "har baar jab main wahan jati hu",
                         "jab aas paas koi nahi hota", "jab se yeh naukri shuru ki"],
                "extra": ["main dar ke maare chilla bhi nahi payi", "gharwalo ko nahi bataya",
                          "kehta hai koi yakeen nahi karega", "naukri ki zarurat hai isliye chup rahi"],
            },
            "patterns": [
                "{who} {when} {act}",
                "{when} {who} {act}",
                "{who} {act} aur {extra}",
                "{extra}, {who} {when} {act}",
                "kisi ko batana zaruri hai — {who} {when} {act}",
            ],
        },
    },
    # ----------------------------------------------------------------
    "intimidation_threat": {
        "en": {
            "slots": {
                "who": ["he", "my husband", "my in laws", "his family", "my ex",
                        "my brother", "the men he sent"],
                "act": ["threatens me", "says he will hurt my family", "threatens to take my children",
                        "warns me not to tell anyone", "follows me to work",
                        "waits outside my house", "checks my phone every night",
                        "says he will ruin my name", "threatens to throw me out",
                        "says the police will do nothing", "keeps calling from new numbers",
                        "does not let me go anywhere alone"],
                "when": ["every time i talk about leaving", "if i mention the police",
                         "whenever i speak to my parents", "constantly", "since i complained",
                         "after i said i would get help", "all week"],
            },
            "patterns": [
                "{who} {act} {when}",
                "{when} {who} {act}",
                "{who} {act} and i am frightened",
                "{who} {act}, that is why i have not gone to anyone",
                "i am calling quietly because {who} {act}",
                "{who} {act} {when} and it is getting worse",
            ],
        },
        "hi": {
            "slots": {
                "who": ["वो", "मेरे पति", "मेरे ससुराल वाले", "उसका परिवार", "मेरा पुराना पति",
                        "मेरा भाई", "उसके भेजे आदमी"],
                "act": ["मुझे धमकाता है", "कहता है परिवार को नुकसान पहुंचाएगा",
                        "बच्चों को छीन लेने की धमकी देता है", "किसी को बताने से मना करता है",
                        "काम पर पीछे आता है", "घर के बाहर इंतजार करता है",
                        "रोज रात फोन चेक करता है", "कहता है बदनाम कर दूंगा",
                        "घर से निकाल देने की धमकी देता है", "कहता है पुलिस कुछ नहीं करेगी",
                        "नए नंबरों से फोन करता रहता है", "अकेले कहीं जाने नहीं देता"],
                "when": ["जब भी मैं जाने की बात करती हूं", "अगर पुलिस का नाम लूं",
                         "जब भी मायके बात करती हूं", "लगातार", "जब से शिकायत की",
                         "मदद लेने की बात कहने के बाद", "पूरे हफ्ते"],
            },
            "patterns": [
                "{who} {when} {act}",
                "{when} {who} {act}",
                "{who} {act} और मुझे डर लगता है",
                "{who} {act}, इसीलिए मैं किसी के पास नहीं गई",
                "मैं धीरे से फोन कर रही हूं क्योंकि {who} {act}",
            ],
        },
        "gu": {
            "slots": {
                "who": ["એ", "મારા પતિ", "મારા સાસરિયાં", "એનો પરિવાર", "મારો ભાઈ"],
                "act": ["મને ધમકાવે છે", "કહે છે પરિવારને નુકસાન કરશે",
                        "બાળકો છીનવી લેવાની ધમકી આપે છે", "કોઈને કહેવાની ના પાડે છે",
                        "કામ પર પાછળ આવે છે", "ઘર બહાર રાહ જુએ છે",
                        "રોજ રાત્રે ફોન ચેક કરે છે", "કહે છે બદનામ કરી દઈશ",
                        "ઘરમાંથી કાઢી મૂકવાની ધમકી આપે છે", "એકલા ક્યાંય જવા દેતો નથી"],
                "when": ["જ્યારે પણ જવાની વાત કરું", "જો પોલીસનું નામ લઉં",
                         "જ્યારે પિયર વાત કરું", "સતત", "જ્યારથી ફરિયાદ કરી", "આખું અઠવાડિયું"],
            },
            "patterns": [
                "{who} {when} {act}",
                "{when} {who} {act}",
                "{who} {act} અને મને ડર લાગે છે",
                "{who} {act}, એટલે જ હું કોઈની પાસે નથી ગઈ",
            ],
        },
        "rom": {
            "slots": {
                "who": ["wo", "mere pati", "mere sasural wale", "uska parivar", "mera bhai",
                        "uske bheje aadmi", "mara sasariya"],
                "act": ["mujhe dhamkata hai", "kehta hai parivar ko nuksaan pahunchayega",
                        "bachho ko chheen lene ki dhamki deta hai", "kisi ko batane se mana karta hai",
                        "kaam par peeche aata hai", "ghar ke bahar intezaar karta hai",
                        "roz raat phone check karta hai", "kehta hai badnaam kar dunga",
                        "ghar se nikal dene ki dhamki deta hai", "kehta hai police kuch nahi karegi",
                        "naye number se phone karta rehta hai", "akele kahin jane nahi deta"],
                "when": ["jab bhi main jane ki baat karti hu", "agar police ka naam lu",
                         "jab bhi maayke baat karti hu", "lagatar", "jab se shikayat ki",
                         "pure hafte"],
            },
            "patterns": [
                "{who} {when} {act}",
                "{when} {who} {act}",
                "{who} {act} aur mujhe dar lagta hai",
                "{who} {act}, isiliye main kisi ke paas nahi gayi",
                "main dheere se phone kar rahi hu kyunki {who} {act}",
            ],
        },
    },
    # ----------------------------------------------------------------
    "severe_trauma_fear": {
        "en": {
            "slots": {
                "sym": ["my hands shake", "my chest goes tight", "i cannot breathe properly",
                        "i start sweating", "i freeze completely", "i feel sick",
                        "i cannot stop crying", "my heart races", "i jump at every sound"],
                "trig": ["when i hear the gate", "every time the phone rings",
                         "when someone walks behind me", "when i have to go home",
                         "when his name comes up", "at night", "when i see a man who looks like him",
                         "before he comes back from work"],
                "extra": ["i have not slept properly in weeks", "i keep checking the lock",
                          "i cannot go down that street anymore", "i keep reliving it",
                          "i am frightened all the time", "i sleep with the light on"],
            },
            "patterns": [
                "{sym} {trig}",
                "{trig} {sym}",
                "{sym} {trig} and {extra}",
                "{extra}, and {sym} {trig}",
                "i am scared — {sym} {trig}",
                "{extra}",
            ],
        },
        "hi": {
            "slots": {
                "sym": ["मेरे हाथ कांपने लगते हैं", "सीने में जकड़न हो जाती है",
                        "सांस नहीं ले पाती", "पसीना आने लगता है", "मैं जड़ हो जाती हूं",
                        "जी घबराता है", "रोना नहीं रुकता", "दिल तेज धड़कने लगता है",
                        "हर आवाज पर चौंक जाती हूं"],
                "trig": ["जब गेट की आवाज आती है", "जब भी फोन बजता है",
                         "जब कोई पीछे से आता है", "जब घर जाना होता है",
                         "जब उसका नाम आता है", "रात में", "जब उस जैसा कोई दिखता है",
                         "उसके काम से लौटने से पहले"],
                "extra": ["हफ्तों से ठीक से नींद नहीं आई", "बार बार ताला चेक करती हूं",
                          "अब उस गली से नहीं जा सकती", "वही सब बार बार याद आता है",
                          "हर वक्त डर लगा रहता है", "लाइट जलाकर सोती हूं"],
            },
            "patterns": [
                "{trig} {sym}",
                "{sym} {trig}",
                "{trig} {sym} और {extra}",
                "{extra}, और {trig} {sym}",
                "मुझे डर लगता है — {trig} {sym}",
                "{extra}",
            ],
        },
        "gu": {
            "slots": {
                "sym": ["મારા હાથ ધ્રૂજે છે", "છાતીમાં જકડાઈ જાય છે",
                        "શ્વાસ નથી લેવાતો", "પરસેવો વળી જાય છે", "હું જડ થઈ જાઉં છું",
                        "જીવ ગભરાય છે", "રડવું બંધ નથી થતું", "હૃદય ઝડપથી ધબકે છે"],
                "trig": ["જ્યારે ગેટનો અવાજ આવે", "જ્યારે પણ ફોન વાગે",
                         "જ્યારે કોઈ પાછળથી આવે", "જ્યારે ઘરે જવાનું હોય",
                         "જ્યારે એનું નામ આવે", "રાત્રે", "એના જેવો કોઈ દેખાય ત્યારે"],
                "extra": ["અઠવાડિયાંથી બરાબર ઊંઘ નથી", "વારંવાર તાળું ચેક કરું છું",
                          "હવે એ ગલીમાં નથી જઈ શકતી", "એ જ બધું વારંવાર યાદ આવે છે",
                          "દર વખતે ડર લાગ્યા કરે છે"],
            },
            "patterns": [
                "{trig} {sym}",
                "{sym} {trig}",
                "{trig} {sym} અને {extra}",
                "{extra}, અને {trig} {sym}",
                "{extra}",
            ],
        },
        "rom": {
            "slots": {
                "sym": ["mere haath kaanpne lagte hain", "seene me jakadan ho jati hai",
                        "saans nahi le pati", "paseena aane lagta hai", "main jad ho jati hu",
                        "jee ghabrata hai", "rona nahi rukta", "dil tez dhadakne lagta hai",
                        "har awaaz pe chaunk jati hu"],
                "trig": ["jab gate ki awaaz aati hai", "jab bhi phone bajta hai",
                         "jab koi peeche se aata hai", "jab ghar jana hota hai",
                         "jab uska naam aata hai", "raat me", "jab us jaisa koi dikhta hai"],
                "extra": ["hafto se theek se neend nahi aayi", "baar baar tala check karti hu",
                          "ab us gali se nahi ja sakti", "wahi sab baar baar yaad aata hai",
                          "har waqt dar laga rehta hai", "light jalakar soti hu"],
            },
            "patterns": [
                "{trig} {sym}",
                "{sym} {trig}",
                "{trig} {sym} aur {extra}",
                "{extra}, aur {trig} {sym}",
                "mujhe dar lagta hai — {trig} {sym}",
                "{extra}",
            ],
        },
    },
    # ----------------------------------------------------------------
    "depression_hopelessness": {
        "en": {
            "slots": {
                "sym": ["i cannot get out of bed", "i have no energy for anything",
                        "nothing interests me anymore", "i cry for no reason",
                        "i feel completely empty", "i feel worthless",
                        "i cannot concentrate on anything", "everything feels pointless",
                        "i have stopped eating properly", "i feel like a burden"],
                "dur": ["for the last few months", "for weeks now", "since it happened",
                        "most days", "every single day", "since the beginning of the year"],
                "extra": ["i do not see it getting better", "i have stopped talking to people",
                          "i have not left the house", "i used to be different",
                          "i do not recognise myself anymore"],
            },
            "patterns": [
                "{sym} {dur}",
                "{dur} {sym}",
                "{sym} and {extra}",
                "{extra}, {sym} {dur}",
                "{sym}, {dur}, and {extra}",
            ],
        },
        "hi": {
            "slots": {
                "sym": ["बिस्तर से उठा नहीं जाता", "किसी काम की ताकत नहीं",
                        "अब किसी चीज में मन नहीं लगता", "बिना वजह रोना आता है",
                        "अंदर से बिल्कुल खाली लगता है", "खुद को बेकार समझती हूं",
                        "किसी चीज पर ध्यान नहीं लगता", "सब बेमतलब लगता है",
                        "ठीक से खाना छोड़ दिया है", "लगता है मैं बोझ हूं"],
                "dur": ["पिछले कुछ महीनों से", "कई हफ्तों से", "जब से यह हुआ",
                        "ज्यादातर दिन", "हर रोज", "साल की शुरुआत से"],
                "extra": ["लगता नहीं कि कुछ ठीक होगा", "लोगों से बात करना बंद कर दिया",
                          "घर से बाहर नहीं निकली", "पहले मैं ऐसी नहीं थी",
                          "अब खुद को पहचान नहीं पाती"],
            },
            "patterns": [
                "{dur} {sym}",
                "{sym} {dur}",
                "{sym} और {extra}",
                "{extra}, {dur} {sym}",
            ],
        },
        "gu": {
            "slots": {
                "sym": ["પથારીમાંથી ઊઠી શકાતું નથી", "કોઈ કામની શક્તિ નથી",
                        "હવે કશામાં મન લાગતું નથી", "કારણ વગર રડવું આવે છે",
                        "અંદરથી સાવ ખાલી લાગે છે", "મને નકામી લાગું છું",
                        "કશા પર ધ્યાન નથી લાગતું", "બધું અર્થહીન લાગે છે",
                        "બરાબર જમવાનું છોડી દીધું છે"],
                "dur": ["છેલ્લા થોડા મહિનાથી", "કેટલાય અઠવાડિયાંથી", "જ્યારથી આ થયું",
                        "મોટાભાગના દિવસો", "દરરોજ"],
                "extra": ["લાગતું નથી કે કંઈ સારું થશે", "લોકો સાથે વાત કરવાનું બંધ કર્યું",
                          "ઘરની બહાર નથી નીકળી", "પહેલાં હું આવી નહોતી"],
            },
            "patterns": [
                "{dur} {sym}",
                "{sym} {dur}",
                "{sym} અને {extra}",
                "{extra}, {dur} {sym}",
            ],
        },
        "rom": {
            "slots": {
                "sym": ["bistar se utha nahi jata", "kisi kaam ki taakat nahi",
                        "ab kisi cheez me mann nahi lagta", "bina wajah rona aata hai",
                        "andar se bilkul khali lagta hai", "khud ko bekaar samajhti hu",
                        "kisi cheez par dhyan nahi lagta", "sab bematlab lagta hai",
                        "theek se khana chhod diya hai", "lagta hai main bojh hu"],
                "dur": ["pichle kuch mahino se", "kai hafto se", "jab se yeh hua",
                        "zyadatar din", "har roz", "saal ki shuruaat se"],
                "extra": ["lagta nahi ki kuch theek hoga", "logo se baat karna band kar diya",
                          "ghar se bahar nahi nikli", "pehle main aisi nahi thi",
                          "ab khud ko pehchan nahi pati"],
            },
            "patterns": [
                "{dur} {sym}",
                "{sym} {dur}",
                "{sym} aur {extra}",
                "{extra}, {dur} {sym}",
            ],
        },
    },
    # ----------------------------------------------------------------
    "social_isolation": {
        "en": {
            "slots": {
                "state": ["i have nobody to talk to", "i am completely alone",
                          "nobody believes me", "my family has stopped speaking to me",
                          "i am not allowed to see anyone", "i have lost all my friends",
                          "nobody checks on me", "there is no one i can call",
                          "i am cut off from everyone i knew"],
                "why": ["he made sure of it", "since i moved here after marriage",
                        "since i complained", "they told me to adjust and hung up",
                        "because i am not allowed out", "since my mother passed away",
                        "because nobody wants to get involved"],
            },
            "patterns": [
                "{state}, {why}",
                "{why}, and now {state}",
                "{state}",
                "{state} and it has been like this for months",
                "the worst part is {state}",
            ],
        },
        "hi": {
            "slots": {
                "state": ["मेरे पास बात करने वाला कोई नहीं", "मैं बिल्कुल अकेली हूं",
                          "कोई मेरी बात पर यकीन नहीं करता", "घरवालों ने बात करना बंद कर दिया",
                          "मुझे किसी से मिलने नहीं दिया जाता", "मेरे सारे दोस्त छूट गए",
                          "कोई मेरा हाल नहीं पूछता", "कोई नहीं है जिसे मैं फोन कर सकूं"],
                "why": ["उसने ऐसा ही किया", "शादी के बाद यहां आने के बाद से",
                        "जब से मैंने शिकायत की", "उन्होंने एडजस्ट करने को कहकर फोन रख दिया",
                        "क्योंकि मुझे बाहर नहीं जाने देते", "मां के गुजरने के बाद से",
                        "क्योंकि कोई पड़ना नहीं चाहता"],
            },
            "patterns": [
                "{state}, {why}",
                "{why}, और अब {state}",
                "{state}",
                "{state} और महीनों से यही हाल है",
                "सबसे बुरी बात यह है कि {state}",
            ],
        },
        "gu": {
            "slots": {
                "state": ["મારી પાસે વાત કરવા કોઈ નથી", "હું સાવ એકલી છું",
                          "કોઈ મારી વાત માનતું નથી", "ઘરવાળાએ વાત કરવાનું બંધ કર્યું",
                          "મને કોઈને મળવા દેતા નથી", "મારા બધા મિત્રો છૂટી ગયા",
                          "કોઈ મારી ખબર પૂછતું નથી"],
                "why": ["એણે એવું જ કર્યું", "લગ્ન પછી અહીં આવ્યા પછીથી",
                        "જ્યારથી મેં ફરિયાદ કરી", "એમણે એડજસ્ટ કરવાનું કહીને ફોન મૂકી દીધો",
                        "કારણ કે મને બહાર જવા દેતા નથી"],
            },
            "patterns": [
                "{state}, {why}",
                "{why}, અને હવે {state}",
                "{state}",
                "{state} અને મહિનાઓથી આ જ હાલ છે",
            ],
        },
        "rom": {
            "slots": {
                "state": ["mere paas baat karne wala koi nahi", "main bilkul akeli hu",
                          "koi meri baat pe yakeen nahi karta", "gharwalo ne baat karna band kar diya",
                          "mujhe kisi se milne nahi diya jata", "mere saare dost chhoot gaye",
                          "koi mera haal nahi puchta", "koi nahi hai jise main phone kar saku"],
                "why": ["usne aisa hi kiya", "shaadi ke baad yahan aane ke baad se",
                        "jab se maine shikayat ki", "unhone adjust karne ko kehkar phone rakh diya",
                        "kyunki mujhe bahar nahi jane dete", "maa ke guzarne ke baad se"],
            },
            "patterns": [
                "{state}, {why}",
                "{why}, aur ab {state}",
                "{state}",
                "{state} aur mahino se yahi haal hai",
                "sabse buri baat yeh hai ki {state}",
            ],
        },
    },
    # ----------------------------------------------------------------
    "child_safety_concern": {
        "en": {
            "slots": {
                "child": ["my daughter", "my son", "my youngest", "my eight year old",
                          "my niece", "my nephew", "the child next door", "both my children"],
                "sign": ["has marks on her arms", "flinches when he shouts",
                         "has stopped eating", "wets the bed again", "hides when he comes home",
                         "came home with a bruise", "is frightened of him",
                         "has stopped speaking to anyone", "does not want to go to school",
                         "cries every night"],
                "extra": ["the school called me about it", "i do not know who to tell",
                          "he says it is discipline", "i am frightened for her",
                          "nobody in the family will act", "they saw everything last night"],
            },
            "patterns": [
                "{child} {sign}",
                "{child} {sign} and {extra}",
                "{extra} — {child} {sign}",
                "i am calling about {child}, she {sign}",
                "{child} {sign}, this has been going on for weeks",
            ],
        },
        "hi": {
            "slots": {
                "child": ["मेरी बेटी", "मेरा बेटा", "मेरा छोटा बच्चा", "आठ साल की बेटी",
                          "मेरी भतीजी", "मेरा भतीजा", "पड़ोस का बच्चा", "मेरे दोनों बच्चे"],
                "sign": ["के हाथ पर निशान हैं", "उसके चिल्लाने पर सहम जाती है",
                         "ने खाना छोड़ दिया है", "फिर से बिस्तर गीला करती है",
                         "उसके घर आते ही छिप जाता है", "चोट लेकर घर आया",
                         "उससे डरती है", "किसी से बात करना बंद कर दिया है",
                         "स्कूल जाना नहीं चाहती", "हर रात रोती है"],
                "extra": ["स्कूल से इस बारे में फोन आया था", "समझ नहीं आता किसे बताऊं",
                          "वो कहता है यह अनुशासन है", "मुझे उसकी चिंता है",
                          "घर में कोई कुछ नहीं करता", "कल रात उन्होंने सब देखा"],
            },
            "patterns": [
                "{child} {sign}",
                "{child} {sign} और {extra}",
                "{extra} — {child} {sign}",
                "मैं {child} के बारे में फोन कर रही हूं, वो {sign}",
                "{child} {sign}, हफ्तों से यही चल रहा है",
            ],
        },
        "gu": {
            "slots": {
                "child": ["મારી દીકરી", "મારો દીકરો", "મારું નાનું બાળક", "આઠ વર્ષની દીકરી",
                          "મારી ભત્રીજી", "મારો ભત્રીજો", "પડોશનું બાળક"],
                "sign": ["ના હાથ પર નિશાન છે", "એના બૂમો પાડવાથી ડરી જાય છે",
                         "એ જમવાનું છોડી દીધું છે", "ફરી પથારી ભીની કરે છે",
                         "એ ઘરે આવે કે સંતાઈ જાય છે", "વાગેલું લઈને ઘરે આવ્યો",
                         "એનાથી ડરે છે", "કોઈ સાથે વાત કરવાનું બંધ કર્યું છે",
                         "સ્કૂલ જવા નથી માંગતી", "દર રાત્રે રડે છે"],
                "extra": ["સ્કૂલમાંથી આ વિશે ફોન આવ્યો હતો", "સમજાતું નથી કોને કહું",
                          "એ કહે છે આ શિસ્ત છે", "મને એની ચિંતા છે",
                          "ઘરમાં કોઈ કંઈ કરતું નથી"],
            },
            "patterns": [
                "{child} {sign}",
                "{child} {sign} અને {extra}",
                "{extra} — {child} {sign}",
                "{child} {sign}, અઠવાડિયાંથી આ જ ચાલે છે",
            ],
        },
        "rom": {
            "slots": {
                "child": ["meri beti", "mera beta", "mera chhota bacha", "aath saal ki beti",
                          "meri bhatiji", "mera bhatija", "pados ka bacha", "mari dikri"],
                "sign": ["ke haath par nishan hain", "uske chillane par seham jati hai",
                         "ne khana chhod diya hai", "phir se bistar geela karti hai",
                         "uske ghar aate hi chhup jata hai", "chot lekar ghar aaya",
                         "usse darti hai", "kisi se baat karna band kar diya hai",
                         "school jana nahi chahti", "har raat roti hai"],
                "extra": ["school se is baare me phone aaya tha", "samajh nahi aata kise bataun",
                          "wo kehta hai yeh anushasan hai", "mujhe uski chinta hai",
                          "ghar me koi kuch nahi karta"],
            },
            "patterns": [
                "{child} {sign}",
                "{child} {sign} aur {extra}",
                "{extra} — {child} {sign}",
                "main {child} ke baare me phone kar rahi hu, wo {sign}",
                "{child} {sign}, hafto se yahi chal raha hai",
            ],
        },
    },
    # ----------------------------------------------------------------
    "elder_abuse": {
        "en": {
            "slots": {
                "elder": ["my mother", "my father", "my mother in law", "my grandmother",
                          "my elderly aunt", "my parents", "my grandfather"],
                "act": ["is not being given food properly", "is left alone all day",
                        "is shouted at every day", "is locked in her room",
                        "has not been taken to the doctor in months",
                        "has had her pension taken away", "is being called a burden",
                        "is not given her medicines on time", "is being pushed around"],
                "who": ["by my brother", "by my son", "by my daughter in law",
                        "by the family she lives with", "by her own children", "at home"],
            },
            "patterns": [
                "{elder} {act} {who}",
                "{who}, {elder} {act}",
                "{elder} {act} and nobody will do anything",
                "i am calling about {elder} — she {act} {who}",
                "{elder} {act}, this has gone on long enough",
            ],
        },
        "hi": {
            "slots": {
                "elder": ["मेरी मां", "मेरे पिता", "मेरी सास", "मेरी दादी",
                          "मेरी बुजुर्ग बुआ", "मेरे माता-पिता", "मेरे दादा"],
                "act": ["को ठीक से खाना नहीं दिया जाता", "को पूरे दिन अकेला छोड़ दिया जाता है",
                        "पर रोज चिल्लाते हैं", "को कमरे में बंद कर देते हैं",
                        "को महीनों से डॉक्टर के पास नहीं ले गए",
                        "की पेंशन छीन ली गई है", "को बोझ कहा जाता है",
                        "को दवाई समय पर नहीं दी जाती", "के साथ धक्का-मुक्की होती है"],
                "who": ["मेरे भाई द्वारा", "मेरे बेटे द्वारा", "बहू द्वारा",
                        "जिस परिवार के साथ रहती हैं उनके द्वारा", "अपने ही बच्चों द्वारा", "घर में"],
            },
            "patterns": [
                "{elder} {act} {who}",
                "{who}, {elder} {act}",
                "{elder} {act} और कोई कुछ नहीं करता",
                "मैं {elder} के बारे में फोन कर रही हूं — उन्हें {act}",
                "{elder} {act}, अब बहुत हो गया",
            ],
        },
        "gu": {
            "slots": {
                "elder": ["મારી મમ્મી", "મારા પપ્પા", "મારી સાસુ", "મારી દાદી",
                          "મારા વૃદ્ધ ફોઈ", "મારા માતા-પિતા"],
                "act": ["ને બરાબર જમવાનું નથી અપાતું", "ને આખો દિવસ એકલા મૂકી દેવાય છે",
                        "પર રોજ બૂમો પાડે છે", "ને રૂમમાં પૂરી દે છે",
                        "ને મહિનાઓથી ડોક્ટર પાસે નથી લઈ ગયા",
                        "નું પેન્શન છીનવી લીધું છે", "ને બોજ કહેવાય છે",
                        "ને દવા સમયસર નથી અપાતી"],
                "who": ["મારા ભાઈ દ્વારા", "મારા દીકરા દ્વારા", "વહુ દ્વારા",
                        "પોતાના જ બાળકો દ્વારા", "ઘરમાં"],
            },
            "patterns": [
                "{elder} {act} {who}",
                "{who}, {elder} {act}",
                "{elder} {act} અને કોઈ કંઈ કરતું નથી",
                "{elder} {act}, હવે બહુ થયું",
            ],
        },
        "rom": {
            "slots": {
                "elder": ["meri maa", "mere papa", "meri saas", "meri dadi",
                          "meri budhi bua", "mere maa baap", "mari mummy"],
                "act": ["ko theek se khana nahi diya jata", "ko pure din akela chhod dete hain",
                        "par roz chillate hain", "ko room me band kar dete hain",
                        "ko mahino se doctor ke paas nahi le gaye",
                        "ki pension chheen li gayi hai", "ko bojh kaha jata hai",
                        "ko dawai samay par nahi di jati"],
                "who": ["mere bhai dwara", "mere bete dwara", "bahu dwara",
                        "apne hi bachho dwara", "ghar me"],
            },
            "patterns": [
                "{elder} {act} {who}",
                "{who}, {elder} {act}",
                "{elder} {act} aur koi kuch nahi karta",
                "main {elder} ke baare me phone kar rahi hu — unhe {act}",
            ],
        },
    },
    # ----------------------------------------------------------------
    "financial_exploitation": {
        "en": {
            "slots": {
                "act": ["takes my entire salary", "does not let me keep any money",
                        "controls every rupee i earn", "sold my jewellery without telling me",
                        "took a loan in my name", "made me sign papers i could not read",
                        "keeps demanding dowry", "will not let me work",
                        "has taken my bank passbook", "spent all my savings",
                        "took my pension money", "asks for money from my parents"],
                "who": ["my husband", "my in laws", "my brother", "my son", "his family"],
                "extra": ["i have to ask for bus fare", "i have nothing in my name",
                          "i worked for years and kept none of it",
                          "they say it was not enough", "i cannot even buy medicine"],
            },
            "patterns": [
                "{who} {act}",
                "{who} {act} and {extra}",
                "{extra} — {who} {act}",
                "{who} {act}, it has been like this since the wedding",
                "{who} {act} and i have no way to manage",
            ],
        },
        "hi": {
            "slots": {
                "act": ["मेरी पूरी तनख्वाह ले लेता है", "मुझे पैसे रखने नहीं देता",
                        "मेरी कमाई का एक एक रुपया अपने पास रखता है",
                        "मेरे गहने बिना बताए बेच दिए", "मेरे नाम पर कर्ज लिया",
                        "ऐसे कागजों पर दस्तखत करवाए जो मैं पढ़ नहीं सकी",
                        "लगातार दहेज मांगता है", "मुझे काम नहीं करने देता",
                        "मेरी बैंक पासबुक ले ली", "मेरी सारी बचत खर्च कर दी",
                        "मेरी पेंशन के पैसे ले लिए", "मेरे मायके से पैसे मांगता है"],
                "who": ["मेरे पति", "मेरे ससुराल वाले", "मेरा भाई", "मेरा बेटा", "उसका परिवार"],
                "extra": ["बस के पैसे भी मांगने पड़ते हैं", "मेरे नाम पर कुछ नहीं है",
                          "सालों काम किया पर कुछ नहीं रखा", "कहते हैं कम मिला",
                          "दवाई तक नहीं खरीद सकती"],
            },
            "patterns": [
                "{who} {act}",
                "{who} {act} और {extra}",
                "{extra} — {who} {act}",
                "{who} {act}, शादी के बाद से यही हाल है",
                "{who} {act} और मेरे पास कोई रास्ता नहीं",
            ],
        },
        "gu": {
            "slots": {
                "act": ["મારો આખો પગાર લઈ લે છે", "મને પૈસા રાખવા દેતો નથી",
                        "મારી કમાણીનો દરેક રૂપિયો પોતાની પાસે રાખે છે",
                        "મારા દાગીના કહ્યા વગર વેચી દીધા", "મારા નામે લોન લીધી",
                        "એવા કાગળો પર સહી કરાવી જે હું વાંચી ન શકી",
                        "સતત દહેજ માંગે છે", "મને કામ કરવા દેતો નથી",
                        "મારી બેંક પાસબુક લઈ લીધી", "મારી બધી બચત વાપરી નાખી"],
                "who": ["મારા પતિ", "મારા સાસરિયાં", "મારો ભાઈ", "મારો દીકરો"],
                "extra": ["બસના પૈસા પણ માંગવા પડે છે", "મારા નામે કંઈ નથી",
                          "વર્ષો કામ કર્યું પણ કંઈ ન રાખ્યું", "કહે છે ઓછું મળ્યું"],
            },
            "patterns": [
                "{who} {act}",
                "{who} {act} અને {extra}",
                "{extra} — {who} {act}",
                "{who} {act}, લગ્ન પછીથી આ જ હાલ છે",
            ],
        },
        "rom": {
            "slots": {
                "act": ["meri puri tankhwah le leta hai", "mujhe paise rakhne nahi deta",
                        "meri kamai ka ek ek rupaya apne paas rakhta hai",
                        "mere gehne bina bataye bech diye", "mere naam par karz liya",
                        "aise kaagzo par dastkhat karwaye jo main padh nahi saki",
                        "lagatar dahej maangta hai", "mujhe kaam nahi karne deta",
                        "meri bank passbook le li", "meri saari bachat kharch kar di"],
                "who": ["mere pati", "mere sasural wale", "mera bhai", "mera beta", "uska parivar"],
                "extra": ["bus ke paise bhi maangne padte hain", "mere naam par kuch nahi hai",
                          "saalo kaam kiya par kuch nahi rakha", "kehte hain kam mila",
                          "dawai tak nahi khareed sakti"],
            },
            "patterns": [
                "{who} {act}",
                "{who} {act} aur {extra}",
                "{extra} — {who} {act}",
                "{who} {act}, shaadi ke baad se yahi haal hai",
            ],
        },
    },
    # ----------------------------------------------------------------
    "legal_dispute": {
        "en": {
            "slots": {
                "issue": ["my brothers have taken the family land",
                          "my name was removed from the property papers",
                          "the police refused to register my complaint",
                          "the landlord is evicting me without notice",
                          "my husbands family is contesting the will",
                          "i need to file for maintenance",
                          "i want custody of my children",
                          "the builder has not given possession",
                          "someone forged my signature on the sale deed",
                          "i have received a court summons",
                          "the panchayat decided against me without hearing me",
                          "i need to file an fir but they keep sending me away"],
                "extra": ["i cannot afford a lawyer", "i do not understand the papers",
                          "i have been to the office four times",
                          "nobody will tell me what to do next",
                          "the free legal aid lawyer never comes",
                          "i do not know which court it is"],
            },
            "patterns": [
                "{issue} and {extra}",
                "{issue}",
                "{extra} — {issue}",
                "i need legal help, {issue}",
                "{issue}, what are my options",
            ],
        },
        "hi": {
            "slots": {
                "issue": ["भाइयों ने पुश्तैनी जमीन ले ली",
                          "संपत्ति के कागजों से मेरा नाम हटा दिया गया",
                          "पुलिस ने मेरी शिकायत दर्ज करने से मना कर दिया",
                          "मकान मालिक बिना नोटिस घर खाली करवा रहा है",
                          "पति के परिवार ने वसीयत पर सवाल उठाया है",
                          "मुझे गुजारा भत्ता के लिए अर्जी देनी है",
                          "मुझे बच्चों की कस्टडी चाहिए",
                          "बिल्डर ने कब्जा नहीं दिया",
                          "किसी ने बिक्री के कागज पर मेरे फर्जी दस्तखत किए",
                          "मुझे कोर्ट का समन आया है",
                          "पंचायत ने मेरी बात सुने बिना फैसला दे दिया",
                          "एफआईआर लिखवानी है पर बार बार लौटा देते हैं"],
                "extra": ["वकील का खर्च नहीं उठा सकती", "कागज समझ नहीं आते",
                          "चार बार दफ्तर जा चुकी हूं",
                          "कोई नहीं बताता आगे क्या करना है",
                          "सरकारी वकील कभी नहीं आता"],
            },
            "patterns": [
                "{issue} और {extra}",
                "{issue}",
                "{extra} — {issue}",
                "मुझे कानूनी मदद चाहिए, {issue}",
                "{issue}, मेरे पास क्या रास्ते हैं",
            ],
        },
        "gu": {
            "slots": {
                "issue": ["ભાઈઓએ વડીલોની જમીન લઈ લીધી",
                          "મિલકતના કાગળમાંથી મારું નામ કાઢી નાખ્યું",
                          "પોલીસે મારી ફરિયાદ નોંધવાની ના પાડી",
                          "મકાનમાલિક નોટિસ વગર ઘર ખાલી કરાવે છે",
                          "મારે ભરણપોષણ માટે અરજી કરવી છે",
                          "મારે બાળકોની કસ્ટડી જોઈએ",
                          "બિલ્ડરે કબજો નથી આપ્યો",
                          "મને કોર્ટનું સમન્સ આવ્યું છે",
                          "એફઆઈઆર લખાવવી છે પણ વારંવાર પાછી મોકલે છે"],
                "extra": ["વકીલનો ખર્ચ ઉઠાવી શકતી નથી", "કાગળો સમજાતા નથી",
                          "ચાર વાર ઓફિસ જઈ આવી છું",
                          "કોઈ કહેતું નથી આગળ શું કરવું"],
            },
            "patterns": [
                "{issue} અને {extra}",
                "{issue}",
                "{extra} — {issue}",
                "મારે કાનૂની મદદ જોઈએ, {issue}",
            ],
        },
        "rom": {
            "slots": {
                "issue": ["bhaiyo ne pushtaini zameen le li",
                          "sampatti ke kaagzo se mera naam hata diya gaya",
                          "police ne meri shikayat darj karne se mana kar diya",
                          "makaan malik bina notice ghar khali karwa raha hai",
                          "mujhe guzara bhatta ke liye arji deni hai",
                          "mujhe bachho ki custody chahiye",
                          "builder ne kabza nahi diya",
                          "mujhe court ka samman aaya hai",
                          "fir likhwani hai par baar baar lauta dete hain"],
                "extra": ["wakeel ka kharcha nahi utha sakti", "kaagaz samajh nahi aate",
                          "chaar baar daftar ja chuki hu",
                          "koi nahi batata aage kya karna hai",
                          "sarkari wakeel kabhi nahi aata"],
            },
            "patterns": [
                "{issue} aur {extra}",
                "{issue}",
                "{extra} — {issue}",
                "mujhe kanooni madad chahiye, {issue}",
                "{issue}, mere paas kya raste hain",
            ],
        },
    },
    # ----------------------------------------------------------------
    "workplace_harassment": {
        "en": {
            "slots": {
                "who": ["my manager", "my supervisor", "the site in charge", "my team lead",
                        "the owner", "a senior colleague"],
                "act": ["shouts abuse at me", "keeps me back late for no reason",
                        "has stopped paying my wages", "cut my name from the roster after i complained",
                        "makes remarks about my caste", "gives me impossible targets on purpose",
                        "threatened to have me fired", "humiliates me in front of everyone",
                        "will not let me take leave", "docked my pay without telling me"],
                "extra": ["hr has done nothing since march", "the complaint letter came back to me",
                          "i was dismissed the week after i reported it",
                          "the internal committee keeps postponing",
                          "i cannot afford to lose this job"],
            },
            "patterns": [
                "{who} {act}",
                "{who} {act} and {extra}",
                "{extra} — {who} {act}",
                "at work {who} {act}",
                "{who} {act}, i do not know who else to tell",
            ],
        },
        "hi": {
            "slots": {
                "who": ["मेरा मैनेजर", "मेरा सुपरवाइजर", "साइट इंचार्ज", "टीम लीड",
                        "मालिक", "एक सीनियर सहकर्मी"],
                "act": ["मुझे गालियां देता है", "बिना वजह देर तक रोकता है",
                        "मेरी तनख्वाह देना बंद कर दिया", "शिकायत के बाद मेरा नाम लिस्ट से हटा दिया",
                        "मेरी जाति को लेकर बातें करता है", "जानबूझकर नामुमकिन टारगेट देता है",
                        "नौकरी से निकलवाने की धमकी दी", "सबके सामने अपमानित करता है",
                        "छुट्टी नहीं लेने देता", "बिना बताए पैसे काट लिए"],
                "extra": ["मार्च से एचआर ने कुछ नहीं किया", "शिकायत पत्र वापस मुझे ही मिल गया",
                          "शिकायत के अगले हफ्ते निकाल दिया",
                          "आंतरिक समिति की बैठक टलती रहती है",
                          "यह नौकरी नहीं छोड़ सकती"],
            },
            "patterns": [
                "{who} {act}",
                "{who} {act} और {extra}",
                "{extra} — {who} {act}",
                "काम पर {who} {act}",
                "{who} {act}, समझ नहीं आता किसे बताऊं",
            ],
        },
        "gu": {
            "slots": {
                "who": ["મારો મેનેજર", "મારો સુપરવાઈઝર", "સાઈટ ઈન્ચાર્જ", "ટીમ લીડ", "માલિક"],
                "act": ["મને ગાળો દે છે", "કારણ વગર મોડે સુધી રોકે છે",
                        "મારો પગાર આપવાનું બંધ કર્યું", "ફરિયાદ પછી મારું નામ લિસ્ટમાંથી કાઢ્યું",
                        "મારી જાતિ વિશે બોલે છે", "જાણીજોઈને અશક્ય ટાર્ગેટ આપે છે",
                        "નોકરીમાંથી કઢાવવાની ધમકી આપી", "બધાની સામે અપમાન કરે છે",
                        "રજા લેવા દેતો નથી"],
                "extra": ["માર્ચથી એચઆરે કંઈ કર્યું નથી", "ફરિયાદનો પત્ર પાછો મને જ મળ્યો",
                          "ફરિયાદના અઠવાડિયામાં કાઢી મૂકી",
                          "આ નોકરી છોડી શકતી નથી"],
            },
            "patterns": [
                "{who} {act}",
                "{who} {act} અને {extra}",
                "{extra} — {who} {act}",
                "કામ પર {who} {act}",
            ],
        },
        "rom": {
            "slots": {
                "who": ["mera manager", "mera supervisor", "site incharge", "team lead",
                        "malik", "ek senior colleague"],
                "act": ["mujhe gaaliyan deta hai", "bina wajah der tak rokta hai",
                        "meri tankhwah dena band kar diya", "shikayat ke baad mera naam list se hata diya",
                        "meri jaati ko lekar baatein karta hai", "jaanbujhkar namumkin target deta hai",
                        "naukri se nikalwane ki dhamki di", "sabke saamne apmanit karta hai",
                        "chhutti nahi lene deta"],
                "extra": ["march se hr ne kuch nahi kiya", "shikayat patra wapas mujhe hi mil gaya",
                          "shikayat ke agle hafte nikal diya",
                          "yeh naukri nahi chhod sakti"],
            },
            "patterns": [
                "{who} {act}",
                "{who} {act} aur {extra}",
                "{extra} — {who} {act}",
                "kaam par {who} {act}",
                "{who} {act}, samajh nahi aata kise bataun",
            ],
        },
    },
    # ----------------------------------------------------------------
    "cybercrime_online_abuse": {
        "en": {
            "slots": {
                "act": ["someone made a fake profile with my photos",
                        "he is threatening to post my private pictures",
                        "my account was hacked and the password changed",
                        "a video of me is being shared in groups",
                        "he morphed my face onto other pictures",
                        "my phone number is being posted on websites",
                        "i get abusive messages from new accounts every day",
                        "someone cloned my whatsapp",
                        "he is asking for money or he will send the photos to my family",
                        "they are tagging my office in posts about me"],
                "extra": ["i do not know how to stop it", "i have screenshots of everything",
                          "the cyber cell asked me to come back later",
                          "i am terrified my family will see",
                          "it has been going on for two weeks",
                          "i do not even know who is doing it"],
            },
            "patterns": [
                "{act} and {extra}",
                "{act}",
                "{extra} — {act}",
                "{act}, please tell me what to do",
            ],
        },
        "hi": {
            "slots": {
                "act": ["किसी ने मेरी फोटो से फर्जी प्रोफाइल बना दी",
                        "वो मेरी निजी तस्वीरें डालने की धमकी दे रहा है",
                        "मेरा अकाउंट हैक हो गया और पासवर्ड बदल दिया",
                        "मेरा वीडियो ग्रुपों में फैलाया जा रहा है",
                        "मेरा चेहरा दूसरी तस्वीरों पर लगा दिया",
                        "मेरा नंबर वेबसाइटों पर डाला जा रहा है",
                        "रोज नए अकाउंट से गालियां आती हैं",
                        "किसी ने मेरा व्हाट्सएप क्लोन कर लिया",
                        "पैसे मांग रहा है वरना फोटो घरवालों को भेजेगा"],
                "extra": ["समझ नहीं आता कैसे रोकूं", "मेरे पास सब स्क्रीनशॉट हैं",
                          "साइबर सेल ने बाद में आने को कहा",
                          "डर है घरवाले देख लेंगे",
                          "दो हफ्ते से यही चल रहा है",
                          "पता ही नहीं कौन कर रहा है"],
            },
            "patterns": [
                "{act} और {extra}",
                "{act}",
                "{extra} — {act}",
                "{act}, बताइए क्या करूं",
            ],
        },
        "gu": {
            "slots": {
                "act": ["કોઈએ મારા ફોટાથી બનાવટી પ્રોફાઈલ બનાવી",
                        "એ મારા ખાનગી ફોટા મૂકવાની ધમકી આપે છે",
                        "મારું એકાઉન્ટ હેક થયું અને પાસવર્ડ બદલાઈ ગયો",
                        "મારો વીડિયો ગ્રુપમાં ફેલાવાય છે",
                        "મારો ચહેરો બીજા ફોટા પર લગાવ્યો",
                        "મારો નંબર વેબસાઈટ પર મૂકાય છે",
                        "રોજ નવા એકાઉન્ટથી ગાળો આવે છે",
                        "પૈસા માંગે છે નહીં તો ફોટા ઘરે મોકલશે"],
                "extra": ["સમજાતું નથી કેવી રીતે રોકું", "મારી પાસે બધા સ્ક્રીનશોટ છે",
                          "સાયબર સેલે પછી આવવાનું કહ્યું",
                          "ડર છે ઘરવાળા જોઈ જશે"],
            },
            "patterns": [
                "{act} અને {extra}",
                "{act}",
                "{extra} — {act}",
            ],
        },
        "rom": {
            "slots": {
                "act": ["kisi ne meri photo se fake profile bana di",
                        "wo meri private photos daalne ki dhamki de raha hai",
                        "mera account hack ho gaya aur password badal diya",
                        "mera video groupo me failaya ja raha hai",
                        "mera chehra dusri tasveero par laga diya",
                        "mera number websites par daala ja raha hai",
                        "roz naye account se gaaliyan aati hain",
                        "kisi ne mera whatsapp clone kar liya",
                        "paise maang raha hai warna photo gharwalo ko bhejega"],
                "extra": ["samajh nahi aata kaise roku", "mere paas sab screenshot hain",
                          "cyber cell ne baad me aane ko kaha",
                          "dar hai gharwale dekh lenge",
                          "do hafte se yahi chal raha hai"],
            },
            "patterns": [
                "{act} aur {extra}",
                "{act}",
                "{extra} — {act}",
                "{act}, bataiye kya karu",
            ],
        },
    },
    # ----------------------------------------------------------------
    "substance_related": {
        "en": {
            "slots": {
                "who": ["my husband", "my son", "my brother", "my father", "he"],
                "act": ["drinks every night", "comes home drunk", "spends the whole wage on drink",
                        "has started using something", "is drunk by the time he gets home",
                        "sold things from the house for his habit",
                        "is only like this after drinking", "drinks and then the shouting starts"],
                "extra": ["when he is sober he apologises", "the trouble always starts after that",
                          "there are bottles hidden all over the house",
                          "he is a different person then",
                          "the children are frightened of him at night",
                          "he says he will stop and never does"],
            },
            "patterns": [
                "{who} {act}",
                "{who} {act} and {extra}",
                "{extra} — {who} {act}",
                "{who} {act}, that is when it happens",
            ],
        },
        "hi": {
            "slots": {
                "who": ["मेरे पति", "मेरा बेटा", "मेरा भाई", "मेरे पिता", "वो"],
                "act": ["रोज रात शराब पीता है", "पीकर घर आता है", "पूरी मजदूरी शराब में उड़ा देता है",
                        "कुछ नशा करने लगा है", "घर पहुंचते पहुंचते नशे में होता है",
                        "नशे के लिए घर का सामान बेच दिया",
                        "सिर्फ पीने के बाद ऐसा होता है", "पीता है और फिर चिल्लाना शुरू"],
                "extra": ["होश में आकर माफी मांगता है", "झगड़ा हमेशा उसके बाद शुरू होता है",
                          "घर में जगह जगह बोतलें छिपी हैं",
                          "तब वो बिल्कुल अलग इंसान हो जाता है",
                          "रात में बच्चे उससे डरते हैं",
                          "कहता है छोड़ दूंगा पर कभी नहीं छोड़ता"],
            },
            "patterns": [
                "{who} {act}",
                "{who} {act} और {extra}",
                "{extra} — {who} {act}",
                "{who} {act}, तभी यह सब होता है",
            ],
        },
        "gu": {
            "slots": {
                "who": ["મારા પતિ", "મારો દીકરો", "મારો ભાઈ", "મારા પપ્પા", "એ"],
                "act": ["રોજ રાત્રે દારૂ પીવે છે", "પીને ઘરે આવે છે", "આખી મજૂરી દારૂમાં ઉડાડે છે",
                        "કંઈક નશો કરવા લાગ્યો છે", "ઘરે પહોંચતા સુધીમાં નશામાં હોય છે",
                        "નશા માટે ઘરની વસ્તુઓ વેચી દીધી",
                        "ફક્ત પીધા પછી આવું થાય છે"],
                "extra": ["ભાનમાં આવીને માફી માંગે છે", "ઝઘડો હંમેશા એ પછી શરૂ થાય છે",
                          "ઘરમાં જગ્યાએ જગ્યાએ બોટલો છુપાયેલી છે",
                          "ત્યારે એ સાવ જુદો માણસ થઈ જાય છે",
                          "રાત્રે બાળકો એનાથી ડરે છે"],
            },
            "patterns": [
                "{who} {act}",
                "{who} {act} અને {extra}",
                "{extra} — {who} {act}",
            ],
        },
        "rom": {
            "slots": {
                "who": ["mere pati", "mera beta", "mera bhai", "mere papa", "wo"],
                "act": ["roz raat sharab peeta hai", "peekar ghar aata hai",
                        "puri mazdoori sharab me uda deta hai",
                        "kuch nasha karne laga hai", "ghar pahunchte pahunchte nashe me hota hai",
                        "nashe ke liye ghar ka saman bech diya",
                        "sirf peene ke baad aisa hota hai", "peeta hai aur phir chillana shuru"],
                "extra": ["hosh me aakar maafi maangta hai", "jhagda hamesha uske baad shuru hota hai",
                          "ghar me jagah jagah botlein chhupi hain",
                          "tab wo bilkul alag insaan ho jata hai",
                          "raat me bache usse darte hain"],
            },
            "patterns": [
                "{who} {act}",
                "{who} {act} aur {extra}",
                "{extra} — {who} {act}",
                "{who} {act}, tabhi yeh sab hota hai",
            ],
        },
    },
    # ----------------------------------------------------------------
    "vulnerability_context": {
        "en": {
            "slots": {
                "state": ["i am pregnant", "i am five months pregnant", "i use a wheelchair",
                          "i am seventy years old", "i cannot read or write",
                          "i do not speak the local language", "i have no documents with me",
                          "i am staying in a shelter", "i have been sleeping at the bus stand",
                          "i have two small children with me", "i have no income of my own",
                          "i am new to this city"],
                "extra": ["and i have nowhere to go", "and i depend on them for everything",
                          "and nobody will help me fill the forms",
                          "and i cannot manage on my own",
                          "and i do not know anyone here"],
            },
            "patterns": [
                "{state} {extra}",
                "{state}",
                "{extra}, {state}",
                "please understand, {state} {extra}",
            ],
        },
        "hi": {
            "slots": {
                "state": ["मैं गर्भवती हूं", "मैं पांच महीने की गर्भवती हूं", "मैं व्हीलचेयर पर हूं",
                          "मेरी उम्र सत्तर साल है", "मैं पढ़ना लिखना नहीं जानती",
                          "मुझे यहां की भाषा नहीं आती", "मेरे पास कोई कागज नहीं है",
                          "मैं आश्रय गृह में रह रही हूं", "मैं बस स्टैंड पर सो रही हूं",
                          "मेरे साथ दो छोटे बच्चे हैं", "मेरी अपनी कोई कमाई नहीं",
                          "मैं इस शहर में नई हूं"],
                "extra": ["और मेरे पास जाने की कोई जगह नहीं", "और हर चीज के लिए उन पर निर्भर हूं",
                          "और कोई फॉर्म भरने में मदद नहीं करता",
                          "और मैं अकेले नहीं संभाल सकती",
                          "और यहां किसी को नहीं जानती"],
            },
            "patterns": [
                "{state} {extra}",
                "{state}",
                "{extra}, {state}",
                "समझिए, {state} {extra}",
            ],
        },
        "gu": {
            "slots": {
                "state": ["હું ગર્ભવતી છું", "હું પાંચ મહિનાની ગર્ભવતી છું", "હું વ્હીલચેરમાં છું",
                          "મારી ઉંમર સિત્તેર વર્ષ છે", "હું વાંચી લખી શકતી નથી",
                          "મને અહીંની ભાષા આવડતી નથી", "મારી પાસે કોઈ કાગળ નથી",
                          "હું આશ્રયગૃહમાં રહું છું", "મારી સાથે બે નાનાં બાળકો છે",
                          "મારી પોતાની કોઈ કમાણી નથી"],
                "extra": ["અને મારે જવાની કોઈ જગ્યા નથી", "અને બધા માટે એમના પર નિર્ભર છું",
                          "અને કોઈ ફોર્મ ભરવામાં મદદ કરતું નથી",
                          "અને હું એકલી સંભાળી શકતી નથી"],
            },
            "patterns": [
                "{state} {extra}",
                "{state}",
                "{extra}, {state}",
            ],
        },
        "rom": {
            "slots": {
                "state": ["main pregnant hu", "main paanch mahine ki pregnant hu",
                          "main wheelchair pe hu", "meri umar sattar saal hai",
                          "main padhna likhna nahi jaanti", "mujhe yahan ki bhasha nahi aati",
                          "mere paas koi kaagaz nahi hai", "main shelter home me reh rahi hu",
                          "mere saath do chhote bache hain", "meri apni koi kamai nahi",
                          "main is sheher me nayi hu"],
                "extra": ["aur mere paas jane ki koi jagah nahi", "aur har cheez ke liye un par nirbhar hu",
                          "aur koi form bharne me madad nahi karta",
                          "aur main akele nahi sambhal sakti",
                          "aur yahan kisi ko nahi jaanti"],
            },
            "patterns": [
                "{state} {extra}",
                "{state}",
                "{extra}, {state}",
                "samajhiye, {state} {extra}",
            ],
        },
    },
}


# SIH26093 atrocity categories (Round 19) — see atrocity_data.py.
from atrocity_data import ATROCITY_TEMPLATES  # noqa: E402

TEMPLATES.update(ATROCITY_TEMPLATES)
